# Generated by Django 5.1.5 on 2025-02-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_sent',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent email sent for this product.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_date',
            field=models.DateTimeField(blank=True, help_text='When the product was first or newly offered. User can edit if re-offered.', null=True),
        ),
    ]
