# Generated by Django 5.1.5 on 2025-02-04 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_last_sent_product_offer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When the product was first or newly offered. User can edit if re-offered.', null=True),
        ),
    ]
