"""
Seed script to populate the furniture database with products from specified vendor brands.
Product information based on publicly available catalog data.
"""
import psycopg2
from psycopg2.extras import RealDictCursor
from datetime import datetime, timedelta
import random

# Database connection - use Docker service name when running in container
DB_CONFIG = {
    "dbname": "npp_furniture",
    "user": "postgres",
    "password": "26,Sheetpans!",
    "host": "npp_furniture-db",
    "port": 5432
}

# Products from specified vendor brands
VENDOR_PRODUCTS = [
    # ===== 9to5 Seating =====
    {
        "title": "9to5 Seating Vault 1460 Task Chair",
        "category": "Chairs",
        "vendor": "9to5 Seating",
        "price": 385.00,
        "moq": 1,
        "qty": 18,
        "sku": "9T5-VAULT-1460",
        "upc": "789012345001",
        "lead_time": "3-5 Business Days",
        "fob": "Jasper, IN",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Mesh/Fabric",
        "color": "Black",
        "brand": "9to5 Seating",
        "width": 26,
        "depth": 26,
        "height": 42,
        "weight": 38,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Synchro-tilt", "Adjustable lumbar", "4D arms", "Seat slider"],
    },
    {
        "title": "9to5 Seating Aria 1880 High-Back",
        "category": "Chairs",
        "vendor": "9to5 Seating",
        "price": 445.00,
        "moq": 1,
        "qty": 12,
        "sku": "9T5-ARIA-1880",
        "upc": "789012345002",
        "lead_time": "3-5 Business Days",
        "fob": "Jasper, IN",
        "image_url": "https://images.unsplash.com/photo-1589884629038-b631346a23c0?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Graphite",
        "brand": "9to5 Seating",
        "width": 27,
        "depth": 27,
        "height": 46,
        "weight": 42,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full mesh back", "Waterfall seat", "Chrome base", "Headrest"],
    },
    {
        "title": "9to5 Seating Luna 2140 Guest Chair",
        "category": "Chairs",
        "vendor": "9to5 Seating",
        "price": 265.00,
        "moq": 2,
        "qty": 24,
        "sku": "9T5-LUNA-2140",
        "upc": "789012345003",
        "lead_time": "3-5 Business Days",
        "fob": "Jasper, IN",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Fabric/Steel",
        "color": "Navy",
        "brand": "9to5 Seating",
        "width": 24,
        "depth": 24,
        "height": 34,
        "weight": 28,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Sled base", "Stackable", "Wall saver legs"],
    },

    # ===== AIS (Affordable Interior Systems) =====
    {
        "title": "AIS Calibrate Series 6x6 Workstation",
        "category": "Cubicles & Partitions",
        "vendor": "AIS",
        "price": 1295.00,
        "moq": 1,
        "qty": 10,
        "sku": "AIS-CAL-6X6",
        "upc": "789012345010",
        "lead_time": "7-10 Business Days",
        "fob": "Leominster, MA",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Designer White",
        "brand": "AIS",
        "width": 72,
        "depth": 72,
        "height": 54,
        "weight": 275,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Tackable fabric", "Integrated power", "Tool-less reconfiguration"],
    },
    {
        "title": "AIS Divi Linear Open Plan 4-Pack",
        "category": "Cubicles & Partitions",
        "vendor": "AIS",
        "price": 2895.00,
        "moq": 1,
        "qty": 5,
        "sku": "AIS-DIVI-4PK",
        "upc": "789012345011",
        "lead_time": "10-14 Business Days",
        "fob": "Leominster, MA",
        "image_url": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Laminate/Aluminum",
        "color": "Walnut/White",
        "brand": "AIS",
        "width": 240,
        "depth": 60,
        "height": 29,
        "weight": 420,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["4 workstations", "Privacy screens", "Power spine", "Cable management"],
    },
    {
        "title": "AIS Element Executive Desk 72 inch",
        "category": "Desks",
        "vendor": "AIS",
        "price": 895.00,
        "moq": 1,
        "qty": 8,
        "sku": "AIS-ELEM-72",
        "upc": "789012345012",
        "lead_time": "5-7 Business Days",
        "fob": "Leominster, MA",
        "image_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Espresso",
        "brand": "AIS",
        "width": 72,
        "depth": 30,
        "height": 29,
        "weight": 165,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full modesty panel", "Grommet holes", "Scratch resistant"],
    },

    # ===== Allermuir =====
    {
        "title": "Allermuir Open Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Allermuir",
        "price": 1695.00,
        "moq": 1,
        "qty": 4,
        "sku": "ALM-OPEN-LNG",
        "upc": "789012345020",
        "lead_time": "10-14 Business Days",
        "fob": "High Point, NC",
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Fabric/Wood",
        "color": "Ocean Blue",
        "brand": "Allermuir",
        "width": 32,
        "depth": 30,
        "height": 32,
        "weight": 55,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": False,
        "features": ["Oak frame", "Premium upholstery", "Minimalist design"],
    },
    {
        "title": "Allermuir Fifty Series Bench 60 inch",
        "category": "Lounge & Reception",
        "vendor": "Allermuir",
        "price": 1295.00,
        "moq": 1,
        "qty": 6,
        "sku": "ALM-50-BN60",
        "upc": "789012345021",
        "lead_time": "7-10 Business Days",
        "fob": "High Point, NC",
        "image_url": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800",
        "room_type": "Lobby",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Charcoal",
        "brand": "Allermuir",
        "width": 60,
        "depth": 24,
        "height": 17,
        "weight": 65,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": False,
        "features": ["2-seat bench", "Powder-coated base", "High-density foam"],
    },

    # ===== American Seating =====
    {
        "title": "American Seating Acton Stack Chair",
        "category": "Chairs",
        "vendor": "American Seating",
        "price": 185.00,
        "moq": 4,
        "qty": 48,
        "sku": "AS-ACTON-STK",
        "upc": "789012345030",
        "lead_time": "3-5 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Training Room",
        "style": "Contemporary",
        "material": "Plastic/Steel",
        "color": "Black",
        "brand": "American Seating",
        "width": 21,
        "depth": 22,
        "height": 32,
        "weight": 12,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": False,
        "features": ["Stacks 12 high", "Ganging glides", "BIFMA certified"],
    },
    {
        "title": "American Seating Academy 4-Leg Chair",
        "category": "Chairs",
        "vendor": "American Seating",
        "price": 225.00,
        "moq": 4,
        "qty": 36,
        "sku": "AS-ACAD-4LG",
        "upc": "789012345031",
        "lead_time": "3-5 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800",
        "room_type": "Training Room",
        "style": "Modern",
        "material": "Polypropylene/Steel",
        "color": "Navy",
        "brand": "American Seating",
        "width": 22,
        "depth": 22,
        "height": 33,
        "weight": 14,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": False,
        "features": ["Flex back", "Tablet arm optional", "Caster option"],
    },

    # ===== Arcadia =====
    {
        "title": "Arcadia Nios Task Chair",
        "category": "Chairs",
        "vendor": "Arcadia",
        "price": 495.00,
        "moq": 1,
        "qty": 15,
        "sku": "ARC-NIOS-TSK",
        "upc": "789012345040",
        "lead_time": "5-7 Business Days",
        "fob": "Los Angeles, CA",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Slate",
        "brand": "Arcadia",
        "width": 26,
        "depth": 26,
        "height": 43,
        "weight": 40,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Synchro-tilt", "Adjustable lumbar", "Weight-activated"],
    },
    {
        "title": "Arcadia Vero Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Arcadia",
        "price": 1295.00,
        "moq": 1,
        "qty": 6,
        "sku": "ARC-VERO-LNG",
        "upc": "789012345041",
        "lead_time": "7-10 Business Days",
        "fob": "Los Angeles, CA",
        "image_url": "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Leather/Wood",
        "color": "Cognac",
        "brand": "Arcadia",
        "width": 30,
        "depth": 32,
        "height": 30,
        "weight": 58,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": False,
        "features": ["Full-grain leather", "Solid wood arms", "High-resilience foam"],
    },

    # ===== Artopex =====
    {
        "title": "Artopex Take Off Conference Table 96 inch",
        "category": "Tables",
        "vendor": "Artopex",
        "price": 1895.00,
        "moq": 1,
        "qty": 4,
        "sku": "ATX-TKOFF-96",
        "upc": "789012345050",
        "lead_time": "10-14 Business Days",
        "fob": "Montreal, QC",
        "image_url": "https://images.unsplash.com/photo-1462826303086-329426d1aef5?w=800",
        "room_type": "Conference Room",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Walnut",
        "brand": "Artopex",
        "width": 96,
        "depth": 48,
        "height": 29,
        "weight": 185,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Boat shape", "Integrated power", "Cable management", "Seats 8"],
    },
    {
        "title": "Artopex Aria Private Office Suite",
        "category": "Desks",
        "vendor": "Artopex",
        "price": 2495.00,
        "moq": 1,
        "qty": 3,
        "sku": "ATX-ARIA-STE",
        "upc": "789012345051",
        "lead_time": "14-21 Business Days",
        "fob": "Montreal, QC",
        "image_url": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Veneer/Steel",
        "color": "Dark Walnut",
        "brand": "Artopex",
        "width": 72,
        "depth": 36,
        "height": 29,
        "weight": 245,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Return included", "Credenza", "Hutch optional", "Premium veneer"],
    },

    # ===== Boss Design =====
    {
        "title": "Boss Design Coza Task Chair",
        "category": "Chairs",
        "vendor": "Boss Design",
        "price": 895.00,
        "moq": 1,
        "qty": 8,
        "sku": "BD-COZA-TSK",
        "upc": "789012345060",
        "lead_time": "7-10 Business Days",
        "fob": "Dudley, UK",
        "image_url": "https://images.unsplash.com/photo-1589884629038-b631346a23c0?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Graphite",
        "brand": "Boss Design",
        "width": 27,
        "depth": 27,
        "height": 45,
        "weight": 42,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": True,
        "features": ["Self-adjusting", "4D arms", "Lumbar support", "Polished base"],
    },
    {
        "title": "Boss Design Agent High-Back Chair",
        "category": "Chairs",
        "vendor": "Boss Design",
        "price": 1295.00,
        "moq": 1,
        "qty": 5,
        "sku": "BD-AGENT-HB",
        "upc": "789012345061",
        "lead_time": "10-14 Business Days",
        "fob": "Dudley, UK",
        "image_url": "https://images.unsplash.com/photo-1541558869434-2840d308329a?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Leather/Aluminum",
        "color": "Black",
        "brand": "Boss Design",
        "width": 28,
        "depth": 28,
        "height": 52,
        "weight": 52,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": True,
        "features": ["Executive styling", "Memory foam", "Integrated headrest", "Die-cast arms"],
    },

    # ===== Cabot Wrenn =====
    {
        "title": "Cabot Wrenn Sylis Executive Chair",
        "category": "Chairs",
        "vendor": "Cabot Wrenn",
        "price": 1695.00,
        "moq": 1,
        "qty": 4,
        "sku": "CW-SYLIS-EX",
        "upc": "789012345070",
        "lead_time": "10-14 Business Days",
        "fob": "Hickory, NC",
        "image_url": "https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Leather/Wood",
        "color": "Burgundy",
        "brand": "Cabot Wrenn",
        "width": 28,
        "depth": 30,
        "height": 48,
        "weight": 62,
        "condition": "New",
        "warranty": "Lifetime",
        "assembly_required": False,
        "features": ["Top-grain leather", "Solid wood trim", "High-density foam"],
    },
    {
        "title": "Cabot Wrenn Husk Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Cabot Wrenn",
        "price": 2295.00,
        "moq": 1,
        "qty": 3,
        "sku": "CW-HUSK-LNG",
        "upc": "789012345071",
        "lead_time": "14-21 Business Days",
        "fob": "Hickory, NC",
        "image_url": "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Fabric/Wood",
        "color": "Sage Green",
        "brand": "Cabot Wrenn",
        "width": 36,
        "depth": 34,
        "height": 34,
        "weight": 68,
        "condition": "New",
        "warranty": "Lifetime",
        "assembly_required": False,
        "features": ["Sculptural design", "Solid hardwood", "COM available"],
    },

    # ===== Cherryman =====
    {
        "title": "Cherryman Amber Executive L-Desk",
        "category": "Desks",
        "vendor": "Cherryman",
        "price": 1195.00,
        "moq": 1,
        "qty": 8,
        "sku": "CM-AMBER-L72",
        "upc": "789012345080",
        "lead_time": "5-7 Business Days",
        "fob": "City of Industry, CA",
        "image_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Laminate/Steel",
        "color": "Mahogany",
        "brand": "Cherryman",
        "width": 72,
        "depth": 78,
        "height": 29,
        "weight": 195,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["48 inch return", "Box/box/file pedestals", "Grommet holes"],
    },
    {
        "title": "Cherryman Verde 6x6 Panel System",
        "category": "Cubicles & Partitions",
        "vendor": "Cherryman",
        "price": 1095.00,
        "moq": 1,
        "qty": 12,
        "sku": "CM-VERDE-6X6",
        "upc": "789012345081",
        "lead_time": "7-10 Business Days",
        "fob": "City of Industry, CA",
        "image_url": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Fabric/Steel",
        "color": "Slate Gray",
        "brand": "Cherryman",
        "width": 72,
        "depth": 72,
        "height": 54,
        "weight": 255,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Tackable panels", "Power ready", "Multiple heights"],
    },
    {
        "title": "Cherryman Jade Conference Table 120 inch",
        "category": "Tables",
        "vendor": "Cherryman",
        "price": 1695.00,
        "moq": 1,
        "qty": 4,
        "sku": "CM-JADE-120",
        "upc": "789012345082",
        "lead_time": "7-10 Business Days",
        "fob": "City of Industry, CA",
        "image_url": "https://images.unsplash.com/photo-1577412647305-991150c7d163?w=800",
        "room_type": "Conference Room",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "White",
        "brand": "Cherryman",
        "width": 120,
        "depth": 48,
        "height": 29,
        "weight": 225,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Power/data ready", "Cable management", "Seats 10-12"],
    },

    # ===== Compel =====
    {
        "title": "Compel Argos Task Chair",
        "category": "Chairs",
        "vendor": "Compel",
        "price": 425.00,
        "moq": 1,
        "qty": 20,
        "sku": "CMP-ARGOS-TSK",
        "upc": "789012345090",
        "lead_time": "3-5 Business Days",
        "fob": "Los Angeles, CA",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Black",
        "brand": "Compel",
        "width": 26,
        "depth": 26,
        "height": 43,
        "weight": 38,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full mesh back", "Adjustable lumbar", "Synchro-tilt", "Quick ship"],
    },
    {
        "title": "Compel Derby Conference Chair",
        "category": "Chairs",
        "vendor": "Compel",
        "price": 345.00,
        "moq": 4,
        "qty": 24,
        "sku": "CMP-DERBY-CF",
        "upc": "789012345091",
        "lead_time": "3-5 Business Days",
        "fob": "Los Angeles, CA",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Conference Room",
        "style": "Contemporary",
        "material": "Fabric/Steel",
        "color": "Navy",
        "brand": "Compel",
        "width": 24,
        "depth": 25,
        "height": 36,
        "weight": 32,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Sled base", "Memory foam", "Chrome frame"],
    },

    # ===== Deflecto =====
    {
        "title": "Deflecto EconoMat Chair Mat 46x60",
        "category": "Accessories",
        "vendor": "Deflecto",
        "price": 89.00,
        "moq": 1,
        "qty": 50,
        "sku": "DEF-ECONO-4660",
        "upc": "789012345100",
        "lead_time": "3-5 Business Days",
        "fob": "Indianapolis, IN",
        "image_url": "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Vinyl",
        "color": "Clear",
        "brand": "Deflecto",
        "width": 46,
        "depth": 60,
        "height": 0.125,
        "weight": 12,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Low pile carpet", "Gripper back", "Beveled edges"],
    },
    {
        "title": "Deflecto SuperMat Chair Mat 45x53",
        "category": "Accessories",
        "vendor": "Deflecto",
        "price": 145.00,
        "moq": 1,
        "qty": 35,
        "sku": "DEF-SUPER-4553",
        "upc": "789012345101",
        "lead_time": "3-5 Business Days",
        "fob": "Indianapolis, IN",
        "image_url": "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Polycarbonate",
        "color": "Clear",
        "brand": "Deflecto",
        "width": 45,
        "depth": 53,
        "height": 0.125,
        "weight": 14,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Medium pile carpet", "Studded back", "Lip included"],
    },

    # ===== Egan Visual =====
    {
        "title": "Egan V-Series Glass Board 48x72",
        "category": "Accessories",
        "vendor": "Egan Visual",
        "price": 695.00,
        "moq": 1,
        "qty": 12,
        "sku": "EGN-VSRS-4872",
        "upc": "789012345110",
        "lead_time": "5-7 Business Days",
        "fob": "Oakville, ON",
        "image_url": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800",
        "room_type": "Conference Room",
        "style": "Modern",
        "material": "Tempered Glass",
        "color": "White",
        "brand": "Egan Visual",
        "width": 72,
        "depth": 0.25,
        "height": 48,
        "weight": 55,
        "condition": "New",
        "warranty": "50 Years",
        "assembly_required": True,
        "features": ["Magnetic", "Ghost-free", "Low-profile mount"],
    },
    {
        "title": "Egan Mobile Whiteboard 72x40",
        "category": "Accessories",
        "vendor": "Egan Visual",
        "price": 895.00,
        "moq": 1,
        "qty": 8,
        "sku": "EGN-MOB-7240",
        "upc": "789012345111",
        "lead_time": "5-7 Business Days",
        "fob": "Oakville, ON",
        "image_url": "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800",
        "room_type": "Training Room",
        "style": "Modern",
        "material": "Steel/Ceramic",
        "color": "White",
        "brand": "Egan Visual",
        "width": 72,
        "depth": 24,
        "height": 72,
        "weight": 85,
        "condition": "New",
        "warranty": "50 Years",
        "assembly_required": True,
        "features": ["Double-sided", "Locking casters", "Magnetic surface"],
    },

    # ===== Encore =====
    {
        "title": "Encore Axial Collaborative Table 60x30",
        "category": "Tables",
        "vendor": "Encore",
        "price": 595.00,
        "moq": 1,
        "qty": 10,
        "sku": "ENC-AXIAL-6030",
        "upc": "789012345120",
        "lead_time": "5-7 Business Days",
        "fob": "Murfreesboro, TN",
        "image_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "White",
        "brand": "Encore",
        "width": 60,
        "depth": 30,
        "height": 29,
        "weight": 75,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Y-leg base", "Power optional", "Cable management"],
    },
    {
        "title": "Encore Motion Height-Adjustable Desk 60x30",
        "category": "Desks",
        "vendor": "Encore",
        "price": 995.00,
        "moq": 1,
        "qty": 12,
        "sku": "ENC-MOT-6030",
        "upc": "789012345121",
        "lead_time": "5-7 Business Days",
        "fob": "Murfreesboro, TN",
        "image_url": "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Maple",
        "brand": "Encore",
        "width": 60,
        "depth": 30,
        "height": 49,
        "weight": 115,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Electric lift", "3 memory presets", "Anti-collision"],
    },

    # ===== Eurotech Seating =====
    {
        "title": "Eurotech iOO Mesh Chair",
        "category": "Chairs",
        "vendor": "Eurotech Seating",
        "price": 595.00,
        "moq": 1,
        "qty": 18,
        "sku": "EUR-IOO-MSH",
        "upc": "789012345130",
        "lead_time": "3-5 Business Days",
        "fob": "Gardena, CA",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Plastic",
        "color": "Black",
        "brand": "Eurotech",
        "width": 27,
        "depth": 27,
        "height": 45,
        "weight": 42,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full mesh", "Adjustable headrest", "Flex-fit lumbar", "4D arms"],
    },
    {
        "title": "Eurotech Vera Task Chair",
        "category": "Chairs",
        "vendor": "Eurotech Seating",
        "price": 425.00,
        "moq": 1,
        "qty": 25,
        "sku": "EUR-VERA-TSK",
        "upc": "789012345131",
        "lead_time": "3-5 Business Days",
        "fob": "Gardena, CA",
        "image_url": "https://images.unsplash.com/photo-1589884629038-b631346a23c0?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Mesh/Fabric",
        "color": "Blue",
        "brand": "Eurotech",
        "width": 26,
        "depth": 26,
        "height": 42,
        "weight": 38,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Mesh back", "Seat slider", "Synchro-tilt", "Quick ship"],
    },
    {
        "title": "Eurotech Apollo High-Back",
        "category": "Chairs",
        "vendor": "Eurotech Seating",
        "price": 295.00,
        "moq": 1,
        "qty": 30,
        "sku": "EUR-APOL-HB",
        "upc": "789012345132",
        "lead_time": "3-5 Business Days",
        "fob": "Gardena, CA",
        "image_url": "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Fabric/Plastic",
        "color": "Charcoal",
        "brand": "Eurotech",
        "width": 25,
        "depth": 25,
        "height": 44,
        "weight": 35,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Ratchet back", "Adjustable arms", "Tilt lock", "Value price"],
    },

    # ===== Fire King =====
    {
        "title": "Fire King 4-Drawer Vertical File",
        "category": "Storage",
        "vendor": "Fire King",
        "price": 1895.00,
        "moq": 1,
        "qty": 6,
        "sku": "FK-4VF-LTR",
        "upc": "789012345140",
        "lead_time": "7-10 Business Days",
        "fob": "New Albany, IN",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Steel",
        "color": "Putty",
        "brand": "Fire King",
        "width": 17.75,
        "depth": 25,
        "height": 52.75,
        "weight": 485,
        "condition": "New",
        "warranty": "Lifetime Fire Protection",
        "assembly_required": False,
        "features": ["1-hour fire rating", "UL Class 350", "Impact rated", "Letter size"],
    },
    {
        "title": "Fire King 2-Drawer Lateral File",
        "category": "Storage",
        "vendor": "Fire King",
        "price": 2495.00,
        "moq": 1,
        "qty": 4,
        "sku": "FK-2LF-44",
        "upc": "789012345141",
        "lead_time": "7-10 Business Days",
        "fob": "New Albany, IN",
        "image_url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Steel",
        "color": "Black",
        "brand": "Fire King",
        "width": 44.5,
        "depth": 22,
        "height": 27.75,
        "weight": 625,
        "condition": "New",
        "warranty": "Lifetime Fire Protection",
        "assembly_required": False,
        "features": ["1-hour fire rating", "UL Class 350", "High-security lock"],
    },

    # ===== Friant =====
    {
        "title": "Friant Interra 6x8 Workstation",
        "category": "Cubicles & Partitions",
        "vendor": "Friant",
        "price": 1495.00,
        "moq": 1,
        "qty": 8,
        "sku": "FRI-INT-6X8",
        "upc": "789012345150",
        "lead_time": "7-10 Business Days",
        "fob": "City of Industry, CA",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Fabric",
        "color": "Graphite/Maple",
        "brand": "Friant",
        "width": 72,
        "depth": 96,
        "height": 54,
        "weight": 295,
        "condition": "New",
        "warranty": "Lifetime",
        "assembly_required": True,
        "features": ["Frameless glass", "Integrated storage", "Power/data spine"],
    },
    {
        "title": "Friant Novo 4-Pack Benching",
        "category": "Cubicles & Partitions",
        "vendor": "Friant",
        "price": 2895.00,
        "moq": 1,
        "qty": 5,
        "sku": "FRI-NOVO-4PK",
        "upc": "789012345151",
        "lead_time": "10-14 Business Days",
        "fob": "City of Industry, CA",
        "image_url": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "White/Walnut",
        "brand": "Friant",
        "width": 240,
        "depth": 60,
        "height": 29,
        "weight": 385,
        "condition": "New",
        "warranty": "Lifetime",
        "assembly_required": True,
        "features": ["4 workstations", "Privacy screens optional", "Power ready"],
    },
    {
        "title": "Friant Dash Executive Desk 72 inch",
        "category": "Desks",
        "vendor": "Friant",
        "price": 895.00,
        "moq": 1,
        "qty": 10,
        "sku": "FRI-DASH-72",
        "upc": "789012345152",
        "lead_time": "5-7 Business Days",
        "fob": "City of Industry, CA",
        "image_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Espresso",
        "brand": "Friant",
        "width": 72,
        "depth": 30,
        "height": 29,
        "weight": 155,
        "condition": "New",
        "warranty": "Lifetime",
        "assembly_required": True,
        "features": ["Modesty panel", "Cable grommets", "Mobile pedestal optional"],
    },

    # ===== Global =====
    {
        "title": "Global Vion High-Back Task Chair",
        "category": "Chairs",
        "vendor": "Global",
        "price": 545.00,
        "moq": 1,
        "qty": 20,
        "sku": "GLB-VION-HB",
        "upc": "789012345160",
        "lead_time": "3-5 Business Days",
        "fob": "Marlton, NJ",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Black",
        "brand": "Global",
        "width": 27,
        "depth": 26,
        "height": 45,
        "weight": 42,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Weight-sensing tilt", "4D arms", "Lumbar support", "Quick ship"],
    },
    {
        "title": "Global G20 Conference Chair",
        "category": "Chairs",
        "vendor": "Global",
        "price": 425.00,
        "moq": 4,
        "qty": 24,
        "sku": "GLB-G20-CF",
        "upc": "789012345161",
        "lead_time": "3-5 Business Days",
        "fob": "Marlton, NJ",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Conference Room",
        "style": "Contemporary",
        "material": "Leather/Aluminum",
        "color": "Black",
        "brand": "Global",
        "width": 25,
        "depth": 26,
        "height": 36,
        "weight": 35,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Sled base", "Chrome frame", "Full arm pads"],
    },
    {
        "title": "Global Princeton Executive Suite",
        "category": "Desks",
        "vendor": "Global",
        "price": 2195.00,
        "moq": 1,
        "qty": 4,
        "sku": "GLB-PRINC-STE",
        "upc": "789012345162",
        "lead_time": "10-14 Business Days",
        "fob": "Marlton, NJ",
        "image_url": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Veneer/Wood",
        "color": "Mahogany",
        "brand": "Global",
        "width": 72,
        "depth": 36,
        "height": 29,
        "weight": 285,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Bow front desk", "Return included", "Credenza with hutch"],
    },
    {
        "title": "Global Evolve Panel System 8x8",
        "category": "Cubicles & Partitions",
        "vendor": "Global",
        "price": 1895.00,
        "moq": 1,
        "qty": 6,
        "sku": "GLB-EVOL-8X8",
        "upc": "789012345163",
        "lead_time": "10-14 Business Days",
        "fob": "Marlton, NJ",
        "image_url": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Neutral",
        "brand": "Global",
        "width": 96,
        "depth": 96,
        "height": 66,
        "weight": 385,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Glass toppers", "Multiple heights", "Power integrated"],
    },

    # ===== HPFI (High Point Furniture Industries) =====
    {
        "title": "HPFI Eve Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "HPFI",
        "price": 895.00,
        "moq": 1,
        "qty": 8,
        "sku": "HPFI-EVE-LNG",
        "upc": "789012345170",
        "lead_time": "5-7 Business Days",
        "fob": "High Point, NC",
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Fabric/Wood",
        "color": "Teal",
        "brand": "HPFI",
        "width": 28,
        "depth": 30,
        "height": 32,
        "weight": 52,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": False,
        "features": ["Solid wood frame", "High-density foam", "COM available"],
    },
    {
        "title": "HPFI Claudia 2-Seat Sofa",
        "category": "Lounge & Reception",
        "vendor": "HPFI",
        "price": 1595.00,
        "moq": 1,
        "qty": 5,
        "sku": "HPFI-CLAUD-2S",
        "upc": "789012345171",
        "lead_time": "7-10 Business Days",
        "fob": "High Point, NC",
        "image_url": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800",
        "room_type": "Lobby",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Charcoal",
        "brand": "HPFI",
        "width": 58,
        "depth": 30,
        "height": 32,
        "weight": 95,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": False,
        "features": ["Modular system", "Power optional", "Ganging capability"],
    },

    # ===== Humanscale =====
    {
        "title": "Humanscale Freedom Headrest Chair",
        "category": "Chairs",
        "vendor": "Humanscale",
        "price": 1295.00,
        "moq": 1,
        "qty": 10,
        "sku": "HS-FREE-HR",
        "upc": "789012345180",
        "lead_time": "5-7 Business Days",
        "fob": "New York, NY",
        "image_url": "https://images.unsplash.com/photo-1589884629038-b631346a23c0?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Fabric/Aluminum",
        "color": "Graphite",
        "brand": "Humanscale",
        "width": 27,
        "depth": 27,
        "height": 51,
        "weight": 40,
        "condition": "New",
        "warranty": "15 Years",
        "assembly_required": True,
        "features": ["Self-adjusting recline", "Weight-sensitive", "Gel seat optional"],
    },
    {
        "title": "Humanscale Diffrient World Chair",
        "category": "Chairs",
        "vendor": "Humanscale",
        "price": 995.00,
        "moq": 1,
        "qty": 12,
        "sku": "HS-DWORLD-BK",
        "upc": "789012345181",
        "lead_time": "5-7 Business Days",
        "fob": "New York, NY",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Die-cast",
        "color": "Black",
        "brand": "Humanscale",
        "width": 26,
        "depth": 26,
        "height": 43,
        "weight": 32,
        "condition": "New",
        "warranty": "15 Years",
        "assembly_required": True,
        "features": ["Tri-panel mesh back", "Form-sensing technology", "Minimal footprint"],
    },
    {
        "title": "Humanscale Float Height-Adjustable Table 60x30",
        "category": "Desks",
        "vendor": "Humanscale",
        "price": 1895.00,
        "moq": 1,
        "qty": 6,
        "sku": "HS-FLOAT-6030",
        "upc": "789012345182",
        "lead_time": "7-10 Business Days",
        "fob": "New York, NY",
        "image_url": "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "White",
        "brand": "Humanscale",
        "width": 60,
        "depth": 30,
        "height": 47,
        "weight": 95,
        "condition": "New",
        "warranty": "15 Years",
        "assembly_required": True,
        "features": ["Counterbalance technology", "No motors", "Instant adjustment"],
    },

    # ===== Innovative =====
    {
        "title": "Innovative Winston Sit-Stand Workstation",
        "category": "Accessories",
        "vendor": "Innovative",
        "price": 795.00,
        "moq": 1,
        "qty": 15,
        "sku": "INN-WINS-WS",
        "upc": "789012345190",
        "lead_time": "3-5 Business Days",
        "fob": "Easton, PA",
        "image_url": "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Aluminum/Steel",
        "color": "Black",
        "brand": "Innovative",
        "width": 36,
        "depth": 24,
        "height": 20,
        "weight": 35,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Dual monitors", "Keyboard tray", "Desk clamp mount"],
    },
    {
        "title": "Innovative Ella Monitor Arm",
        "category": "Accessories",
        "vendor": "Innovative",
        "price": 295.00,
        "moq": 1,
        "qty": 30,
        "sku": "INN-ELLA-ARM",
        "upc": "789012345191",
        "lead_time": "3-5 Business Days",
        "fob": "Easton, PA",
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Aluminum",
        "color": "Silver",
        "brand": "Innovative",
        "width": 4,
        "depth": 18,
        "height": 16,
        "weight": 8,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["27 lb capacity", "360 rotation", "Cable management"],
    },

    # ===== JSI =====
    {
        "title": "JSI Vision Conference Table 120 inch",
        "category": "Tables",
        "vendor": "JSI",
        "price": 2295.00,
        "moq": 1,
        "qty": 3,
        "sku": "JSI-VIS-120",
        "upc": "789012345200",
        "lead_time": "10-14 Business Days",
        "fob": "Jasper, IN",
        "image_url": "https://images.unsplash.com/photo-1577412647305-991150c7d163?w=800",
        "room_type": "Conference Room",
        "style": "Contemporary",
        "material": "Veneer/Steel",
        "color": "Walnut",
        "brand": "JSI",
        "width": 120,
        "depth": 48,
        "height": 29,
        "weight": 265,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["Boat shape", "Integrated power", "Premium veneer", "Seats 10-12"],
    },
    {
        "title": "JSI Flux Height-Adjustable Desk 60x30",
        "category": "Desks",
        "vendor": "JSI",
        "price": 1095.00,
        "moq": 1,
        "qty": 10,
        "sku": "JSI-FLUX-6030",
        "upc": "789012345201",
        "lead_time": "5-7 Business Days",
        "fob": "Jasper, IN",
        "image_url": "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "White",
        "brand": "JSI",
        "width": 60,
        "depth": 30,
        "height": 48,
        "weight": 105,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["Electric lift", "Memory presets", "Quiet motor"],
    },
    {
        "title": "JSI Enzo Executive Desk 72 inch",
        "category": "Desks",
        "vendor": "JSI",
        "price": 1695.00,
        "moq": 1,
        "qty": 5,
        "sku": "JSI-ENZO-72",
        "upc": "789012345202",
        "lead_time": "7-10 Business Days",
        "fob": "Jasper, IN",
        "image_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Veneer/Steel",
        "color": "Dark Walnut",
        "brand": "JSI",
        "width": 72,
        "depth": 36,
        "height": 29,
        "weight": 195,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["Full modesty", "Integrated storage", "Wire management"],
    },

    # ===== Keilhauer =====
    {
        "title": "Keilhauer Sguig Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Keilhauer",
        "price": 1995.00,
        "moq": 1,
        "qty": 4,
        "sku": "KEI-SGUIG-LNG",
        "upc": "789012345210",
        "lead_time": "10-14 Business Days",
        "fob": "Toronto, ON",
        "image_url": "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Fabric/Wood",
        "color": "Moss Green",
        "brand": "Keilhauer",
        "width": 32,
        "depth": 32,
        "height": 30,
        "weight": 58,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": False,
        "features": ["Sculptural design", "Solid ash frame", "High-resilience foam"],
    },
    {
        "title": "Keilhauer Junior Executive Chair",
        "category": "Chairs",
        "vendor": "Keilhauer",
        "price": 895.00,
        "moq": 1,
        "qty": 8,
        "sku": "KEI-JR-EXEC",
        "upc": "789012345211",
        "lead_time": "7-10 Business Days",
        "fob": "Toronto, ON",
        "image_url": "https://images.unsplash.com/photo-1541558869434-2840d308329a?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Leather/Aluminum",
        "color": "Black",
        "brand": "Keilhauer",
        "width": 27,
        "depth": 27,
        "height": 42,
        "weight": 45,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Full-grain leather", "Polished base", "Synchronized tilt"],
    },

    # ===== KFI Seating =====
    {
        "title": "KFI Seating Kool Stack Chair",
        "category": "Chairs",
        "vendor": "KFI Seating",
        "price": 145.00,
        "moq": 4,
        "qty": 60,
        "sku": "KFI-KOOL-STK",
        "upc": "789012345220",
        "lead_time": "3-5 Business Days",
        "fob": "Louisville, KY",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Training Room",
        "style": "Contemporary",
        "material": "Polypropylene/Steel",
        "color": "Navy",
        "brand": "KFI Seating",
        "width": 21,
        "depth": 21,
        "height": 32,
        "weight": 11,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Stacks 8 high", "Perforated back", "Ganging brackets optional"],
    },
    {
        "title": "KFI Seating Imme Task Chair",
        "category": "Chairs",
        "vendor": "KFI Seating",
        "price": 295.00,
        "moq": 1,
        "qty": 25,
        "sku": "KFI-IMME-TSK",
        "upc": "789012345221",
        "lead_time": "3-5 Business Days",
        "fob": "Louisville, KY",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Black",
        "brand": "KFI Seating",
        "width": 25,
        "depth": 25,
        "height": 42,
        "weight": 34,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Mesh back", "Synchro-tilt", "Adjustable arms", "Value price"],
    },

    # ===== KI =====
    {
        "title": "KI Pirouette Swivel Chair",
        "category": "Chairs",
        "vendor": "KI",
        "price": 545.00,
        "moq": 1,
        "qty": 15,
        "sku": "KI-PIROU-SW",
        "upc": "789012345230",
        "lead_time": "5-7 Business Days",
        "fob": "Green Bay, WI",
        "image_url": "https://images.unsplash.com/photo-1589884629038-b631346a23c0?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Graphite",
        "brand": "KI",
        "width": 26,
        "depth": 26,
        "height": 44,
        "weight": 40,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full mesh back", "Lumbar pad", "4D arms", "Quick ship"],
    },
    {
        "title": "KI Maestro Conference Table 96 inch",
        "category": "Tables",
        "vendor": "KI",
        "price": 1695.00,
        "moq": 1,
        "qty": 5,
        "sku": "KI-MAES-96",
        "upc": "789012345231",
        "lead_time": "7-10 Business Days",
        "fob": "Green Bay, WI",
        "image_url": "https://images.unsplash.com/photo-1462826303086-329426d1aef5?w=800",
        "room_type": "Conference Room",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "Designer White",
        "brand": "KI",
        "width": 96,
        "depth": 42,
        "height": 29,
        "weight": 175,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Elliptical shape", "Power optional", "Cable management", "Seats 8"],
    },
    {
        "title": "KI Lightline Panel System 6x6",
        "category": "Cubicles & Partitions",
        "vendor": "KI",
        "price": 1195.00,
        "moq": 1,
        "qty": 10,
        "sku": "KI-LIGHT-6X6",
        "upc": "789012345232",
        "lead_time": "7-10 Business Days",
        "fob": "Green Bay, WI",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Light Gray",
        "brand": "KI",
        "width": 72,
        "depth": 72,
        "height": 54,
        "weight": 245,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Thin profile", "Tool-less assembly", "Multiple finishes"],
    },

    # ===== Krug =====
    {
        "title": "Krug Caldera Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Krug",
        "price": 2295.00,
        "moq": 1,
        "qty": 3,
        "sku": "KRG-CALD-LNG",
        "upc": "789012345240",
        "lead_time": "14-21 Business Days",
        "fob": "Kitchener, ON",
        "image_url": "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Fabric/Wood",
        "color": "Burnt Orange",
        "brand": "Krug",
        "width": 34,
        "depth": 34,
        "height": 32,
        "weight": 65,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": False,
        "features": ["Sculpted wood shell", "Premium upholstery", "Swivel base optional"],
    },
    {
        "title": "Krug Chadwick Conference Table 144 inch",
        "category": "Tables",
        "vendor": "Krug",
        "price": 4995.00,
        "moq": 1,
        "qty": 2,
        "sku": "KRG-CHAD-144",
        "upc": "789012345241",
        "lead_time": "21-28 Business Days",
        "fob": "Kitchener, ON",
        "image_url": "https://images.unsplash.com/photo-1577412647305-991150c7d163?w=800",
        "room_type": "Conference Room",
        "style": "Traditional",
        "material": "Veneer/Wood",
        "color": "Mahogany",
        "brand": "Krug",
        "width": 144,
        "depth": 54,
        "height": 29,
        "weight": 425,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Premium veneer", "Integrated power", "Hand-finished", "Seats 14"],
    },

    # ===== La-Z-Boy Contract =====
    {
        "title": "La-Z-Boy Delano Executive Chair",
        "category": "Chairs",
        "vendor": "La-Z-Boy",
        "price": 795.00,
        "moq": 1,
        "qty": 10,
        "sku": "LZB-DELANO-EX",
        "upc": "789012345250",
        "lead_time": "5-7 Business Days",
        "fob": "Monroe, MI",
        "image_url": "https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Leather/Wood",
        "color": "Coffee Brown",
        "brand": "La-Z-Boy",
        "width": 28,
        "depth": 30,
        "height": 47,
        "weight": 58,
        "condition": "New",
        "warranty": "3 Years",
        "assembly_required": True,
        "features": ["Memory foam", "Ergonomic support", "Wood accents"],
    },
    {
        "title": "La-Z-Boy Baylor Task Chair",
        "category": "Chairs",
        "vendor": "La-Z-Boy",
        "price": 545.00,
        "moq": 1,
        "qty": 15,
        "sku": "LZB-BAYLOR-TSK",
        "upc": "789012345251",
        "lead_time": "5-7 Business Days",
        "fob": "Monroe, MI",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Leather/Steel",
        "color": "Black",
        "brand": "La-Z-Boy",
        "width": 26,
        "depth": 27,
        "height": 44,
        "weight": 45,
        "condition": "New",
        "warranty": "3 Years",
        "assembly_required": True,
        "features": ["Bonded leather", "Lumbar support", "Waterfall seat"],
    },

    # ===== Loftwall =====
    {
        "title": "Loftwall Hush Phone Booth",
        "category": "Cubicles & Partitions",
        "vendor": "Loftwall",
        "price": 4995.00,
        "moq": 1,
        "qty": 4,
        "sku": "LFW-HUSH-PB",
        "upc": "789012345260",
        "lead_time": "14-21 Business Days",
        "fob": "Atlanta, GA",
        "image_url": "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Acoustic Foam",
        "color": "White",
        "brand": "Loftwall",
        "width": 44,
        "depth": 44,
        "height": 90,
        "weight": 485,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": True,
        "features": ["Acoustic privacy", "Ventilation", "Power/USB", "LED lighting"],
    },
    {
        "title": "Loftwall Split Freestanding Screen 60x54",
        "category": "Cubicles & Partitions",
        "vendor": "Loftwall",
        "price": 595.00,
        "moq": 1,
        "qty": 15,
        "sku": "LFW-SPLIT-6054",
        "upc": "789012345261",
        "lead_time": "5-7 Business Days",
        "fob": "Atlanta, GA",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Fabric/Aluminum",
        "color": "Charcoal",
        "brand": "Loftwall",
        "width": 60,
        "depth": 2,
        "height": 54,
        "weight": 28,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": True,
        "features": ["Acoustic", "Freestanding", "Modular", "Multiple colors"],
    },

    # ===== Mayline =====
    {
        "title": "Mayline Medina Executive Desk 72 inch",
        "category": "Desks",
        "vendor": "Mayline",
        "price": 1095.00,
        "moq": 1,
        "qty": 8,
        "sku": "MAY-MED-72",
        "upc": "789012345270",
        "lead_time": "5-7 Business Days",
        "fob": "Sheboygan, WI",
        "image_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "Gray Steel",
        "brand": "Mayline",
        "width": 72,
        "depth": 36,
        "height": 29.5,
        "weight": 175,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full modesty panel", "Cable management", "Mobile pedestal optional"],
    },
    {
        "title": "Mayline Aberdeen Conference Table 96 inch",
        "category": "Tables",
        "vendor": "Mayline",
        "price": 1495.00,
        "moq": 1,
        "qty": 5,
        "sku": "MAY-ABER-96",
        "upc": "789012345271",
        "lead_time": "5-7 Business Days",
        "fob": "Sheboygan, WI",
        "image_url": "https://images.unsplash.com/photo-1462826303086-329426d1aef5?w=800",
        "room_type": "Conference Room",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "Cherry",
        "brand": "Mayline",
        "width": 96,
        "depth": 42,
        "height": 29.5,
        "weight": 165,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Boat shape", "Grommets", "Seats 8"],
    },
    {
        "title": "Mayline ML-Series Flip-N-Go Training Table 60x24",
        "category": "Tables",
        "vendor": "Mayline",
        "price": 395.00,
        "moq": 2,
        "qty": 20,
        "sku": "MAY-ML-6024",
        "upc": "789012345272",
        "lead_time": "3-5 Business Days",
        "fob": "Sheboygan, WI",
        "image_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
        "room_type": "Training Room",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Maple",
        "brand": "Mayline",
        "width": 60,
        "depth": 24,
        "height": 29,
        "weight": 55,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Flip top", "Nesting", "Modesty panel", "Quick ship"],
    },

    # ===== Nucraft =====
    {
        "title": "Nucraft Finn Conference Table 144 inch",
        "category": "Tables",
        "vendor": "Nucraft",
        "price": 5995.00,
        "moq": 1,
        "qty": 2,
        "sku": "NC-FINN-144",
        "upc": "789012345280",
        "lead_time": "21-28 Business Days",
        "fob": "Comstock Park, MI",
        "image_url": "https://images.unsplash.com/photo-1577412647305-991150c7d163?w=800",
        "room_type": "Conference Room",
        "style": "Contemporary",
        "material": "Solid Wood",
        "color": "White Oak",
        "brand": "Nucraft",
        "width": 144,
        "depth": 54,
        "height": 29,
        "weight": 385,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["Solid wood top", "Live edge available", "Integrated technology", "Seats 14"],
    },
    {
        "title": "Nucraft Epono Executive Desk 72 inch",
        "category": "Desks",
        "vendor": "Nucraft",
        "price": 3495.00,
        "moq": 1,
        "qty": 3,
        "sku": "NC-EPON-72",
        "upc": "789012345281",
        "lead_time": "14-21 Business Days",
        "fob": "Comstock Park, MI",
        "image_url": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Veneer/Steel",
        "color": "Walnut",
        "brand": "Nucraft",
        "width": 72,
        "depth": 36,
        "height": 29,
        "weight": 225,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["Premium veneer", "Integrated storage", "Wire management"],
    },

    # ===== Nxtwall =====
    {
        "title": "Nxtwall View Series 10x10 Office",
        "category": "Cubicles & Partitions",
        "vendor": "Nxtwall",
        "price": 8995.00,
        "moq": 1,
        "qty": 2,
        "sku": "NXT-VIEW-10X10",
        "upc": "789012345290",
        "lead_time": "14-21 Business Days",
        "fob": "Kalamazoo, MI",
        "image_url": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Glass/Aluminum",
        "color": "Clear/Silver",
        "brand": "Nxtwall",
        "width": 120,
        "depth": 120,
        "height": 108,
        "weight": 685,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Full glass walls", "Acoustic options", "Sliding door", "Demountable"],
    },
    {
        "title": "Nxtwall Flex Series 8x8 Office",
        "category": "Cubicles & Partitions",
        "vendor": "Nxtwall",
        "price": 6495.00,
        "moq": 1,
        "qty": 3,
        "sku": "NXT-FLEX-8X8",
        "upc": "789012345291",
        "lead_time": "10-14 Business Days",
        "fob": "Kalamazoo, MI",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Laminate/Glass",
        "color": "White/Clear",
        "brand": "Nxtwall",
        "width": 96,
        "depth": 96,
        "height": 96,
        "weight": 545,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Mixed materials", "Sound masking ready", "Relocatable"],
    },

    # ===== Office Star =====
    {
        "title": "Office Star ProGrid High-Back Manager Chair",
        "category": "Chairs",
        "vendor": "Office Star",
        "price": 295.00,
        "moq": 1,
        "qty": 30,
        "sku": "OS-PROG-HB",
        "upc": "789012345300",
        "lead_time": "3-5 Business Days",
        "fob": "City of Industry, CA",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Mesh/Fabric",
        "color": "Black",
        "brand": "Office Star",
        "width": 26,
        "depth": 26,
        "height": 44,
        "weight": 35,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Breathable mesh", "Adjustable arms", "Lumbar support", "Quick ship"],
    },
    {
        "title": "Office Star WorkSmart Guest Chair",
        "category": "Chairs",
        "vendor": "Office Star",
        "price": 175.00,
        "moq": 2,
        "qty": 40,
        "sku": "OS-WORK-GC",
        "upc": "789012345301",
        "lead_time": "3-5 Business Days",
        "fob": "City of Industry, CA",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Fabric/Steel",
        "color": "Black",
        "brand": "Office Star",
        "width": 23,
        "depth": 24,
        "height": 35,
        "weight": 26,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Sled base", "Padded arms", "Value price"],
    },

    # ===== Offices To Go =====
    {
        "title": "Offices To Go Luxhide Executive Chair",
        "category": "Chairs",
        "vendor": "Offices To Go",
        "price": 395.00,
        "moq": 1,
        "qty": 18,
        "sku": "OTG-LUXH-EX",
        "upc": "789012345310",
        "lead_time": "3-5 Business Days",
        "fob": "Marlton, NJ",
        "image_url": "https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Leather/Steel",
        "color": "Black",
        "brand": "Offices To Go",
        "width": 27,
        "depth": 28,
        "height": 46,
        "weight": 48,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Bonded leather", "Pneumatic lift", "Tilt lock", "Padded arms"],
    },
    {
        "title": "Offices To Go Atwork Series Desk 66 inch",
        "category": "Desks",
        "vendor": "Offices To Go",
        "price": 595.00,
        "moq": 1,
        "qty": 12,
        "sku": "OTG-ATW-66",
        "upc": "789012345311",
        "lead_time": "5-7 Business Days",
        "fob": "Marlton, NJ",
        "image_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "Espresso",
        "brand": "Offices To Go",
        "width": 66,
        "depth": 30,
        "height": 29,
        "weight": 145,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full modesty", "Grommets", "Scratch resistant", "Value price"],
    },

    # ===== Peter Pepper =====
    {
        "title": "Peter Pepper IC Light Wall-Mounted Mail Sorter",
        "category": "Storage",
        "vendor": "Peter Pepper",
        "price": 895.00,
        "moq": 1,
        "qty": 8,
        "sku": "PP-ICL-MS12",
        "upc": "789012345320",
        "lead_time": "5-7 Business Days",
        "fob": "Compton, CA",
        "image_url": "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Steel/Aluminum",
        "color": "Silver",
        "brand": "Peter Pepper",
        "width": 36,
        "depth": 6,
        "height": 24,
        "weight": 28,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["12 pockets", "Wall mount", "Powder coated"],
    },
    {
        "title": "Peter Pepper Penguin Waste Receptacle",
        "category": "Accessories",
        "vendor": "Peter Pepper",
        "price": 395.00,
        "moq": 1,
        "qty": 15,
        "sku": "PP-PENG-WR",
        "upc": "789012345321",
        "lead_time": "3-5 Business Days",
        "fob": "Compton, CA",
        "image_url": "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Steel",
        "color": "Stainless",
        "brand": "Peter Pepper",
        "width": 14,
        "depth": 14,
        "height": 32,
        "weight": 18,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["20 gallon", "Swing top", "Recyclable insert"],
    },

    # ===== Safco =====
    {
        "title": "Safco Medina Executive Desk 72 inch",
        "category": "Desks",
        "vendor": "Safco",
        "price": 895.00,
        "moq": 1,
        "qty": 10,
        "sku": "SAF-MED-72",
        "upc": "789012345330",
        "lead_time": "5-7 Business Days",
        "fob": "Minneapolis, MN",
        "image_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "Mocha",
        "brand": "Safco",
        "width": 72,
        "depth": 36,
        "height": 29.5,
        "weight": 165,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full modesty", "Cable management", "Optional return"],
    },
    {
        "title": "Safco Muv Stand-Up Desk",
        "category": "Desks",
        "vendor": "Safco",
        "price": 595.00,
        "moq": 1,
        "qty": 15,
        "sku": "SAF-MUV-SD",
        "upc": "789012345331",
        "lead_time": "3-5 Business Days",
        "fob": "Minneapolis, MN",
        "image_url": "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Gray",
        "brand": "Safco",
        "width": 29.5,
        "depth": 22,
        "height": 45,
        "weight": 55,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Standing height", "Locking casters", "Storage shelf"],
    },
    {
        "title": "Safco Impromptu Mobile Training Table 60x24",
        "category": "Tables",
        "vendor": "Safco",
        "price": 395.00,
        "moq": 2,
        "qty": 18,
        "sku": "SAF-IMP-6024",
        "upc": "789012345332",
        "lead_time": "3-5 Business Days",
        "fob": "Minneapolis, MN",
        "image_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
        "room_type": "Training Room",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Cherry",
        "brand": "Safco",
        "width": 60,
        "depth": 24,
        "height": 29,
        "weight": 48,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Flip top", "Nesting", "Locking casters"],
    },

    # ===== Source International =====
    {
        "title": "Source International Bola Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Source International",
        "price": 1595.00,
        "moq": 1,
        "qty": 5,
        "sku": "SI-BOLA-LNG",
        "upc": "789012345340",
        "lead_time": "7-10 Business Days",
        "fob": "Dallas, TX",
        "image_url": "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Fabric/Steel",
        "color": "Graphite",
        "brand": "Source International",
        "width": 30,
        "depth": 30,
        "height": 30,
        "weight": 52,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": False,
        "features": ["Swivel base", "High-density foam", "COM available"],
    },
    {
        "title": "Source International Node Guest Chair",
        "category": "Chairs",
        "vendor": "Source International",
        "price": 395.00,
        "moq": 2,
        "qty": 16,
        "sku": "SI-NODE-GC",
        "upc": "789012345341",
        "lead_time": "5-7 Business Days",
        "fob": "Dallas, TX",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Fabric/Wood",
        "color": "Navy",
        "brand": "Source International",
        "width": 24,
        "depth": 25,
        "height": 33,
        "weight": 28,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": False,
        "features": ["Solid wood frame", "Stackable", "Multiple finishes"],
    },

    # ===== Spec Furniture =====
    {
        "title": "Spec Westside Modular Sofa 3-Seat",
        "category": "Lounge & Reception",
        "vendor": "Spec",
        "price": 2495.00,
        "moq": 1,
        "qty": 4,
        "sku": "SPEC-WEST-3S",
        "upc": "789012345350",
        "lead_time": "10-14 Business Days",
        "fob": "Toronto, ON",
        "image_url": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Fabric/Wood",
        "color": "Slate",
        "brand": "Spec",
        "width": 78,
        "depth": 32,
        "height": 32,
        "weight": 125,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Modular system", "Power optional", "Solid wood base"],
    },
    {
        "title": "Spec Tangent Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Spec",
        "price": 1295.00,
        "moq": 1,
        "qty": 6,
        "sku": "SPEC-TANG-LNG",
        "upc": "789012345351",
        "lead_time": "7-10 Business Days",
        "fob": "Toronto, ON",
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "room_type": "Lobby",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Teal",
        "brand": "Spec",
        "width": 28,
        "depth": 30,
        "height": 30,
        "weight": 48,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Sled base", "High-resilience foam", "Multiple upholsteries"],
    },

    # ===== Stylex =====
    {
        "title": "Stylex Free Task Chair",
        "category": "Chairs",
        "vendor": "Stylex",
        "price": 695.00,
        "moq": 1,
        "qty": 12,
        "sku": "STX-FREE-TSK",
        "upc": "789012345360",
        "lead_time": "5-7 Business Days",
        "fob": "Willowbrook, IL",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Black",
        "brand": "Stylex",
        "width": 26,
        "depth": 26,
        "height": 44,
        "weight": 40,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Weight-responsive tilt", "4D arms", "Seat depth adjustment"],
    },
    {
        "title": "Stylex Still Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Stylex",
        "price": 1895.00,
        "moq": 1,
        "qty": 4,
        "sku": "STX-STILL-LNG",
        "upc": "789012345361",
        "lead_time": "10-14 Business Days",
        "fob": "Willowbrook, IL",
        "image_url": "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Leather/Wood",
        "color": "Cognac",
        "brand": "Stylex",
        "width": 32,
        "depth": 34,
        "height": 32,
        "weight": 62,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Full-grain leather", "Solid wood frame", "Exceptional comfort"],
    },

    # ===== Symmetry =====
    {
        "title": "Symmetry Amara Height-Adjustable Desk 60x30",
        "category": "Desks",
        "vendor": "Symmetry",
        "price": 895.00,
        "moq": 1,
        "qty": 15,
        "sku": "SYM-AMAR-6030",
        "upc": "789012345370",
        "lead_time": "3-5 Business Days",
        "fob": "Carson, CA",
        "image_url": "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "White",
        "brand": "Symmetry",
        "width": 60,
        "depth": 30,
        "height": 49,
        "weight": 105,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Electric lift", "3 memory presets", "Anti-collision", "Quick ship"],
    },
    {
        "title": "Symmetry Aries Training Table 60x24",
        "category": "Tables",
        "vendor": "Symmetry",
        "price": 345.00,
        "moq": 2,
        "qty": 20,
        "sku": "SYM-ARIES-6024",
        "upc": "789012345371",
        "lead_time": "3-5 Business Days",
        "fob": "Carson, CA",
        "image_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
        "room_type": "Training Room",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "Maple",
        "brand": "Symmetry",
        "width": 60,
        "depth": 24,
        "height": 29,
        "weight": 52,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Flip top", "Nesting", "T-legs", "Quick ship"],
    },

    # ===== Tennsco =====
    {
        "title": "Tennsco Standard Storage Cabinet 36x18x72",
        "category": "Storage",
        "vendor": "Tennsco",
        "price": 495.00,
        "moq": 1,
        "qty": 12,
        "sku": "TEN-STD-361872",
        "upc": "789012345380",
        "lead_time": "3-5 Business Days",
        "fob": "Dickson, TN",
        "image_url": "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=800",
        "room_type": "Open Office",
        "style": "Industrial",
        "material": "Steel",
        "color": "Putty",
        "brand": "Tennsco",
        "width": 36,
        "depth": 18,
        "height": 72,
        "weight": 135,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["4 adjustable shelves", "Locking doors", "Powder coated"],
    },
    {
        "title": "Tennsco 4-Tier Boltless Shelving 48x18x72",
        "category": "Storage",
        "vendor": "Tennsco",
        "price": 295.00,
        "moq": 1,
        "qty": 20,
        "sku": "TEN-BOLT-481872",
        "upc": "789012345381",
        "lead_time": "3-5 Business Days",
        "fob": "Dickson, TN",
        "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
        "room_type": "Open Office",
        "style": "Industrial",
        "material": "Steel",
        "color": "Gray",
        "brand": "Tennsco",
        "width": 48,
        "depth": 18,
        "height": 72,
        "weight": 85,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["No bolts required", "500 lb per shelf", "Adjustable"],
    },

    # ===== Thonet =====
    {
        "title": "Thonet S 64 Cantilever Chair",
        "category": "Chairs",
        "vendor": "Thonet",
        "price": 895.00,
        "moq": 2,
        "qty": 10,
        "sku": "THO-S64-CANT",
        "upc": "789012345390",
        "lead_time": "10-14 Business Days",
        "fob": "Frankenberg, Germany",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Conference Room",
        "style": "Bauhaus",
        "material": "Cane/Chrome",
        "color": "Natural/Chrome",
        "brand": "Thonet",
        "width": 22,
        "depth": 23,
        "height": 32,
        "weight": 12,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": False,
        "features": ["Marcel Breuer design", "Tubular steel", "Cane seat/back", "Classic icon"],
    },
    {
        "title": "Thonet 214 Chair",
        "category": "Chairs",
        "vendor": "Thonet",
        "price": 595.00,
        "moq": 2,
        "qty": 12,
        "sku": "THO-214-BW",
        "upc": "789012345391",
        "lead_time": "10-14 Business Days",
        "fob": "Frankenberg, Germany",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Break Room",
        "style": "Classic",
        "material": "Bentwood/Cane",
        "color": "Natural Beech",
        "brand": "Thonet",
        "width": 17,
        "depth": 20,
        "height": 34,
        "weight": 9,
        "condition": "New",
        "warranty": "5 Years",
        "assembly_required": False,
        "features": ["Iconic design since 1859", "Bentwood construction", "Cane seat"],
    },

    # ===== Via Seating =====
    {
        "title": "Via Seating Genie Task Chair",
        "category": "Chairs",
        "vendor": "Via Seating",
        "price": 495.00,
        "moq": 1,
        "qty": 18,
        "sku": "VIA-GENIE-TSK",
        "upc": "789012345400",
        "lead_time": "3-5 Business Days",
        "fob": "Hayward, CA",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Black",
        "brand": "Via Seating",
        "width": 26,
        "depth": 26,
        "height": 43,
        "weight": 38,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["Full mesh back", "Synchro-tilt", "4D arms", "Quick ship"],
    },
    {
        "title": "Via Seating Run II High-Back Chair",
        "category": "Chairs",
        "vendor": "Via Seating",
        "price": 595.00,
        "moq": 1,
        "qty": 14,
        "sku": "VIA-RUN2-HB",
        "upc": "789012345401",
        "lead_time": "3-5 Business Days",
        "fob": "Hayward, CA",
        "image_url": "https://images.unsplash.com/photo-1589884629038-b631346a23c0?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Mesh/Fabric",
        "color": "Gray",
        "brand": "Via Seating",
        "width": 27,
        "depth": 27,
        "height": 48,
        "weight": 42,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["Adjustable headrest", "Lumbar support", "Weight-sensing tilt"],
    },

    # ===== Zuo Modern =====
    {
        "title": "Zuo Modern Fashion Bar Chair",
        "category": "Chairs",
        "vendor": "Zuo Modern",
        "price": 295.00,
        "moq": 2,
        "qty": 20,
        "sku": "ZUO-FASH-BC",
        "upc": "789012345410",
        "lead_time": "3-5 Business Days",
        "fob": "Los Angeles, CA",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Break Room",
        "style": "Modern",
        "material": "Leather/Chrome",
        "color": "White",
        "brand": "Zuo Modern",
        "width": 18,
        "depth": 18,
        "height": 42,
        "weight": 22,
        "condition": "New",
        "warranty": "1 Year",
        "assembly_required": True,
        "features": ["Adjustable height", "Swivel", "Chrome base", "Footrest"],
    },
    {
        "title": "Zuo Modern Singular Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Zuo Modern",
        "price": 495.00,
        "moq": 1,
        "qty": 10,
        "sku": "ZUO-SING-LNG",
        "upc": "789012345411",
        "lead_time": "3-5 Business Days",
        "fob": "Los Angeles, CA",
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Leatherette/Chrome",
        "color": "Black",
        "brand": "Zuo Modern",
        "width": 28,
        "depth": 28,
        "height": 28,
        "weight": 35,
        "condition": "New",
        "warranty": "1 Year",
        "assembly_required": False,
        "features": ["Low profile", "Chrome frame", "Easy clean surface"],
    },
    {
        "title": "Zuo Modern Pontus Coffee Table",
        "category": "Tables",
        "vendor": "Zuo Modern",
        "price": 395.00,
        "moq": 1,
        "qty": 12,
        "sku": "ZUO-PONT-CT",
        "upc": "789012345412",
        "lead_time": "3-5 Business Days",
        "fob": "Los Angeles, CA",
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "room_type": "Lobby",
        "style": "Modern",
        "material": "Glass/Steel",
        "color": "Clear/Chrome",
        "brand": "Zuo Modern",
        "width": 48,
        "depth": 24,
        "height": 16,
        "weight": 45,
        "condition": "New",
        "warranty": "1 Year",
        "assembly_required": True,
        "features": ["Tempered glass", "Chrome legs", "Modern design"],
    },
]


def connect_db():
    """Connect to the database"""
    return psycopg2.connect(**DB_CONFIG, cursor_factory=RealDictCursor)


def seed_database():
    """Insert all furniture products into the database"""
    conn = connect_db()
    cur = conn.cursor()

    inserted = 0
    skipped = 0

    for product in VENDOR_PRODUCTS:
        # Check if product already exists by SKU
        cur.execute("SELECT id FROM products WHERE sku = %s", (product["sku"],))
        if cur.fetchone():
            print(f"Skipping duplicate: {product['title']} (SKU: {product['sku']})")
            skipped += 1
            continue

        # Generate random dates within the last 30 days
        days_ago = random.randint(0, 30)
        offer_date = datetime.now() - timedelta(days=days_ago)

        # Random expiration date 30-90 days from now
        exp_days = random.randint(30, 90)
        exp_date = (datetime.now() + timedelta(days=exp_days)).strftime("%Y-%m-%d")

        try:
            cur.execute("""
                INSERT INTO products (
                    title, category, vendor, price, moq, qty, sku, upc,
                    lead_time, exp_date, fob, image_url, out_of_stock,
                    offer_date, date_added, room_type, style, material, color, brand,
                    width, depth, height, weight, condition, warranty,
                    assembly_required, features
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
            """, (
                product["title"],
                product["category"],
                product["vendor"],
                product["price"],
                product["moq"],
                product["qty"],
                product["sku"],
                product.get("upc"),
                product["lead_time"],
                exp_date,
                product["fob"],
                product["image_url"],
                False,  # out_of_stock
                offer_date,
                datetime.now(),
                product.get("room_type"),
                product.get("style"),
                product.get("material"),
                product.get("color"),
                product.get("brand"),
                product.get("width"),
                product.get("depth"),
                product.get("height"),
                product.get("weight"),
                product.get("condition", "New"),
                product.get("warranty"),
                product.get("assembly_required", False),
                product.get("features"),
            ))
            inserted += 1
            print(f"Inserted: {product['title']}")
        except Exception as e:
            print(f"Error inserting {product['title']}: {e}")
            conn.rollback()
            continue

    conn.commit()
    cur.close()
    conn.close()

    print(f"\n{'='*50}")
    print(f"Seeding complete!")
    print(f"Inserted: {inserted} products")
    print(f"Skipped: {skipped} duplicates")
    print(f"Total in data: {len(VENDOR_PRODUCTS)}")


if __name__ == "__main__":
    seed_database()
