"""
Seed script to populate the furniture database with realistic office furniture products.
Run this inside the backend container or with access to the database.
"""
import psycopg2
from psycopg2.extras import RealDictCursor
from datetime import datetime, timedelta
import random

# Database connection - use Docker service name when running in container
DB_CONFIG = {
    "dbname": "npp_furniture",
    "user": "postgres",
    "password": "26,Sheetpans!",
    "host": "npp_furniture-db",  # Docker service name
    "port": 5432
}

# Comprehensive office furniture data
FURNITURE_DATA = [
    # ===== EXECUTIVE DESKS =====
    {
        "title": "Steelcase Payback Executive L-Desk",
        "category": "Desks",
        "vendor": "Ideal Office Supply",
        "price": 895.00,
        "moq": 1,
        "qty": 8,
        "sku": "SC-PAYBACK-L72",
        "upc": "886781001234",
        "lead_time": "5-7 Business Days",
        "fob": "Methuen, MA",
        "image_url": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Walnut",
        "brand": "Steelcase",
        "width": 72,
        "depth": 30,
        "height": 29,
        "weight": 185,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Cable management", "Adjustable levelers", "Modesty panel", "Grommet holes"],
    },
    {
        "title": "Herman Miller Canvas Private Office Desk",
        "category": "Desks",
        "vendor": "Office Furniture Liquidators",
        "price": 1250.00,
        "moq": 1,
        "qty": 4,
        "sku": "HM-CANVAS-60",
        "upc": "886781001235",
        "lead_time": "7-10 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Veneer/Aluminum",
        "color": "Dark Walnut",
        "brand": "Herman Miller",
        "width": 60,
        "depth": 30,
        "height": 29,
        "weight": 165,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": False,
        "features": ["Built-in power", "Wire management", "Soft-close drawers"],
    },
    {
        "title": "HON 10500 Series Double Pedestal Desk",
        "category": "Desks",
        "vendor": "National Business Furniture",
        "price": 425.00,
        "moq": 1,
        "qty": 15,
        "sku": "HON-10593-MO",
        "upc": "886781001236",
        "lead_time": "3-5 Business Days",
        "fob": "Chicago, IL",
        "image_url": "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Laminate/Steel",
        "color": "Mocha",
        "brand": "HON",
        "width": 72,
        "depth": 36,
        "height": 29.5,
        "weight": 245,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Full-extension drawers", "Lock included", "Scratch-resistant surface"],
    },
    {
        "title": "Knoll Antenna Workspaces Open Desk",
        "category": "Desks",
        "vendor": "Corporate Interiors",
        "price": 675.00,
        "moq": 2,
        "qty": 12,
        "sku": "KN-ANT-48",
        "upc": "886781001237",
        "lead_time": "5-7 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Aluminum",
        "color": "White",
        "brand": "Knoll",
        "width": 48,
        "depth": 24,
        "height": 29,
        "weight": 95,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Minimalist design", "Cable tray", "Height adjustable legs"],
    },

    # ===== HEIGHT ADJUSTABLE / SIT-STAND DESKS =====
    {
        "title": "Steelcase Migration SE Height-Adjustable Desk",
        "category": "Desks",
        "vendor": "Ergonomic Solutions Inc",
        "price": 1450.00,
        "moq": 1,
        "qty": 6,
        "sku": "SC-MIG-SE60",
        "upc": "886781001238",
        "lead_time": "7-10 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Arctic White",
        "brand": "Steelcase",
        "width": 60,
        "depth": 30,
        "height": 46,
        "weight": 135,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["Electric height adjustment", "Memory presets", "Anti-collision technology", "Quiet motor"],
    },
    {
        "title": "Herman Miller Ratio Sit-Stand Desk",
        "category": "Desks",
        "vendor": "Office Furniture Liquidators",
        "price": 1895.00,
        "moq": 1,
        "qty": 3,
        "sku": "HM-RATIO-72",
        "upc": "886781001239",
        "lead_time": "10-14 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Veneer/Aluminum",
        "color": "Walnut",
        "brand": "Herman Miller",
        "width": 72,
        "depth": 30,
        "height": 50,
        "weight": 165,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["C-leg design", "Programmable presets", "Cable management", "Soft start/stop"],
    },
    {
        "title": "Uplift V2 Commercial Standing Desk Frame",
        "category": "Desks",
        "vendor": "Ergonomic Solutions Inc",
        "price": 599.00,
        "moq": 1,
        "qty": 20,
        "sku": "UPL-V2-BLK",
        "upc": "886781001240",
        "lead_time": "3-5 Business Days",
        "fob": "Austin, TX",
        "image_url": "https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Steel",
        "color": "Black",
        "brand": "Uplift",
        "width": 80,
        "depth": 30,
        "height": 51,
        "weight": 95,
        "condition": "New",
        "warranty": "7 Years",
        "assembly_required": True,
        "features": ["355 lb capacity", "Dual motor", "4 memory presets", "Bluetooth compatible"],
    },

    # ===== TASK CHAIRS =====
    {
        "title": "Herman Miller Aeron Chair Size B",
        "category": "Chairs",
        "vendor": "Office Furniture Liquidators",
        "price": 695.00,
        "moq": 1,
        "qty": 25,
        "sku": "HM-AERON-B",
        "upc": "886781002001",
        "lead_time": "3-5 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Aluminum",
        "color": "Graphite",
        "brand": "Herman Miller",
        "width": 27,
        "depth": 27,
        "height": 41,
        "weight": 41,
        "condition": "Refurbished",
        "warranty": "2 Years",
        "assembly_required": False,
        "features": ["PostureFit SL", "8Z Pellicle", "Fully adjustable arms", "Tilt limiter"],
    },
    {
        "title": "Herman Miller Aeron Chair Size C",
        "category": "Chairs",
        "vendor": "Office Furniture Liquidators",
        "price": 725.00,
        "moq": 1,
        "qty": 18,
        "sku": "HM-AERON-C",
        "upc": "886781002002",
        "lead_time": "3-5 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Aluminum",
        "color": "Graphite",
        "brand": "Herman Miller",
        "width": 28.5,
        "depth": 27,
        "height": 43,
        "weight": 45,
        "condition": "Refurbished",
        "warranty": "2 Years",
        "assembly_required": False,
        "features": ["PostureFit SL", "8Z Pellicle", "Fully adjustable arms", "Large size"],
    },
    {
        "title": "Steelcase Leap V2 Task Chair",
        "category": "Chairs",
        "vendor": "Ideal Office Supply",
        "price": 549.00,
        "moq": 1,
        "qty": 30,
        "sku": "SC-LEAP-V2",
        "upc": "886781002003",
        "lead_time": "3-5 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1589884629038-b631346a23c0?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Black",
        "brand": "Steelcase",
        "width": 27,
        "depth": 24.75,
        "height": 43,
        "weight": 46,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["LiveBack technology", "Natural Glide system", "4-way adjustable arms", "Adjustable lumbar"],
    },
    {
        "title": "Steelcase Gesture Task Chair",
        "category": "Chairs",
        "vendor": "Corporate Interiors",
        "price": 895.00,
        "moq": 1,
        "qty": 10,
        "sku": "SC-GESTURE-BK",
        "upc": "886781002004",
        "lead_time": "5-7 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1541558869434-2840d308329a?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Licorice",
        "brand": "Steelcase",
        "width": 28.5,
        "depth": 23.5,
        "height": 44.25,
        "weight": 51,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": False,
        "features": ["360 arm motion", "Core Equalizer", "Seat slider", "Wrapped back"],
    },
    {
        "title": "Knoll Generation Task Chair",
        "category": "Chairs",
        "vendor": "Corporate Interiors",
        "price": 625.00,
        "moq": 1,
        "qty": 15,
        "sku": "KN-GEN-GRY",
        "upc": "886781002005",
        "lead_time": "5-7 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Plastic",
        "color": "Dark Gray",
        "brand": "Knoll",
        "width": 25,
        "depth": 22,
        "height": 40,
        "weight": 35,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Flex back", "Elastomeric seat", "Dynamic suspension", "Height adjustable"],
    },
    {
        "title": "HON Ignition 2.0 Mid-Back Task Chair",
        "category": "Chairs",
        "vendor": "National Business Furniture",
        "price": 289.00,
        "moq": 1,
        "qty": 40,
        "sku": "HON-IGN2-MB",
        "upc": "886781002006",
        "lead_time": "3-5 Business Days",
        "fob": "Chicago, IL",
        "image_url": "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Mesh/Fabric",
        "color": "Iron Ore",
        "brand": "HON",
        "width": 26.5,
        "depth": 26.5,
        "height": 42,
        "weight": 38,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Ilira-stretch mesh", "Adjustable arms", "Synchro-tilt", "Seat depth adjustment"],
    },
    {
        "title": "Haworth Zody Task Chair",
        "category": "Chairs",
        "vendor": "Ideal Office Supply",
        "price": 475.00,
        "moq": 1,
        "qty": 22,
        "sku": "HW-ZODY-BK",
        "upc": "886781002007",
        "lead_time": "5-7 Business Days",
        "fob": "Holland, MI",
        "image_url": "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Fabric",
        "color": "Black",
        "brand": "Haworth",
        "width": 26,
        "depth": 26,
        "height": 42,
        "weight": 42,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Asymmetrical lumbar", "Pelvic support", "Forward tilt", "4D arms"],
    },

    # ===== EXECUTIVE/CONFERENCE CHAIRS =====
    {
        "title": "Herman Miller Eames Executive Chair",
        "category": "Chairs",
        "vendor": "Office Furniture Liquidators",
        "price": 2450.00,
        "moq": 1,
        "qty": 4,
        "sku": "HM-EAMES-EX",
        "upc": "886781002010",
        "lead_time": "7-10 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=800",
        "room_type": "Private Office",
        "style": "Mid-Century Modern",
        "material": "Leather/Aluminum",
        "color": "Black",
        "brand": "Herman Miller",
        "width": 22.75,
        "depth": 22.5,
        "height": 43,
        "weight": 52,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": False,
        "features": ["Die-cast aluminum", "Premium leather", "Pneumatic lift", "Soft casters"],
    },
    {
        "title": "Knoll Chadwick High-Back Chair",
        "category": "Chairs",
        "vendor": "Corporate Interiors",
        "price": 795.00,
        "moq": 1,
        "qty": 8,
        "sku": "KN-CHAD-HB",
        "upc": "886781002011",
        "lead_time": "5-7 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Mesh/Aluminum",
        "color": "Gray",
        "brand": "Knoll",
        "width": 26.5,
        "depth": 26,
        "height": 47,
        "weight": 48,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Traction seat", "Flexible back", "Height adjustable arms", "Polished base"],
    },

    # ===== CUBICLES & WORKSTATIONS =====
    {
        "title": "Steelcase Answer 6x6 Workstation",
        "category": "Cubicles & Partitions",
        "vendor": "Ideal Office Supply",
        "price": 1250.00,
        "moq": 1,
        "qty": 8,
        "sku": "SC-ANS-6X6",
        "upc": "886781003001",
        "lead_time": "7-10 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Light Gray",
        "brand": "Steelcase",
        "width": 72,
        "depth": 72,
        "height": 54,
        "weight": 285,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["Tackable surfaces", "Integrated power", "Adjustable shelves", "Overhead storage"],
    },
    {
        "title": "Herman Miller Action Office 8x8 System",
        "category": "Cubicles & Partitions",
        "vendor": "Office Furniture Liquidators",
        "price": 1895.00,
        "moq": 1,
        "qty": 5,
        "sku": "HM-AO-8X8",
        "upc": "886781003002",
        "lead_time": "10-14 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Fabric/Aluminum",
        "color": "Neutral",
        "brand": "Herman Miller",
        "width": 96,
        "depth": 96,
        "height": 66,
        "weight": 425,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": True,
        "features": ["Tile system", "Reconfigurable", "Acoustic panels", "Power/data integrated"],
    },
    {
        "title": "Haworth Compose 6x8 Workstation",
        "category": "Cubicles & Partitions",
        "vendor": "Corporate Interiors",
        "price": 1450.00,
        "moq": 2,
        "qty": 12,
        "sku": "HW-COMP-6X8",
        "upc": "886781003003",
        "lead_time": "7-10 Business Days",
        "fob": "Holland, MI",
        "image_url": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Fabric/Steel",
        "color": "Charcoal",
        "brand": "Haworth",
        "width": 72,
        "depth": 96,
        "height": 54,
        "weight": 320,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["Stacking storage", "Height-adjustable surface", "Privacy panels"],
    },
    {
        "title": "Knoll Dividends Horizon 4-Pack Benching",
        "category": "Cubicles & Partitions",
        "vendor": "Corporate Interiors",
        "price": 3200.00,
        "moq": 1,
        "qty": 3,
        "sku": "KN-DIV-4PK",
        "upc": "886781003004",
        "lead_time": "10-14 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Laminate/Aluminum",
        "color": "White/Oak",
        "brand": "Knoll",
        "width": 240,
        "depth": 60,
        "height": 29,
        "weight": 485,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["4 workstations", "Privacy screens", "Shared power spine", "Cable management"],
    },
    {
        "title": "HON Accelerate 6x6 Panel System",
        "category": "Cubicles & Partitions",
        "vendor": "National Business Furniture",
        "price": 895.00,
        "moq": 1,
        "qty": 15,
        "sku": "HON-ACC-6X6",
        "upc": "886781003005",
        "lead_time": "5-7 Business Days",
        "fob": "Chicago, IL",
        "image_url": "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800",
        "room_type": "Open Office",
        "style": "Contemporary",
        "material": "Fabric/Steel",
        "color": "Carbon",
        "brand": "HON",
        "width": 72,
        "depth": 72,
        "height": 53,
        "weight": 265,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Stackable tiles", "Tool-less reconfiguration", "Tackable fabric"],
    },

    # ===== CONFERENCE TABLES =====
    {
        "title": "Steelcase Convene Rectangular Conference Table 12ft",
        "category": "Tables",
        "vendor": "Ideal Office Supply",
        "price": 2450.00,
        "moq": 1,
        "qty": 3,
        "sku": "SC-CONV-144",
        "upc": "886781004001",
        "lead_time": "10-14 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1577412647305-991150c7d163?w=800",
        "room_type": "Conference Room",
        "style": "Modern",
        "material": "Veneer/Steel",
        "color": "Walnut",
        "brand": "Steelcase",
        "width": 144,
        "depth": 48,
        "height": 29,
        "weight": 385,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": True,
        "features": ["Integrated power/data", "Cable management", "Seats 12"],
    },
    {
        "title": "Herman Miller Everywhere Table 8ft",
        "category": "Tables",
        "vendor": "Office Furniture Liquidators",
        "price": 1695.00,
        "moq": 1,
        "qty": 5,
        "sku": "HM-EVERY-96",
        "upc": "886781004002",
        "lead_time": "7-10 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1462826303086-329426d1aef5?w=800",
        "room_type": "Conference Room",
        "style": "Contemporary",
        "material": "Laminate/Aluminum",
        "color": "White",
        "brand": "Herman Miller",
        "width": 96,
        "depth": 42,
        "height": 28.5,
        "weight": 185,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["Y-base legs", "Power grommet ready", "Seats 8"],
    },
    {
        "title": "Knoll Propeller Conference Table 10ft",
        "category": "Tables",
        "vendor": "Corporate Interiors",
        "price": 3250.00,
        "moq": 1,
        "qty": 2,
        "sku": "KN-PROP-120",
        "upc": "886781004003",
        "lead_time": "14-21 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800",
        "room_type": "Conference Room",
        "style": "Modern",
        "material": "Veneer/Steel",
        "color": "Dark Oak",
        "brand": "Knoll",
        "width": 120,
        "depth": 48,
        "height": 29,
        "weight": 295,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": True,
        "features": ["Boat shape", "Premium veneer", "Connectivity box", "Seats 10"],
    },

    # ===== TRAINING/FOLDING TABLES =====
    {
        "title": "HON Huddle Training Table 60x24",
        "category": "Tables",
        "vendor": "National Business Furniture",
        "price": 295.00,
        "moq": 2,
        "qty": 24,
        "sku": "HON-HUD-6024",
        "upc": "886781004010",
        "lead_time": "3-5 Business Days",
        "fob": "Chicago, IL",
        "image_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800",
        "room_type": "Training Room",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "Kingswood Walnut",
        "brand": "HON",
        "width": 60,
        "depth": 24,
        "height": 29,
        "weight": 65,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Flip-top", "Nesting capability", "T-legs", "Casters included"],
    },
    {
        "title": "Steelcase Verb Training Table with Modesty",
        "category": "Tables",
        "vendor": "Ideal Office Supply",
        "price": 425.00,
        "moq": 2,
        "qty": 16,
        "sku": "SC-VERB-72",
        "upc": "886781004011",
        "lead_time": "5-7 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
        "room_type": "Training Room",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Arctic White",
        "brand": "Steelcase",
        "width": 72,
        "depth": 24,
        "height": 29,
        "weight": 78,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["Cable management", "Modesty panel", "Ganging capability", "Power option"],
    },

    # ===== FILE CABINETS =====
    {
        "title": "Steelcase Universal 4-Drawer Lateral File",
        "category": "Storage",
        "vendor": "Ideal Office Supply",
        "price": 595.00,
        "moq": 1,
        "qty": 12,
        "sku": "SC-UNI-4LAT",
        "upc": "886781005001",
        "lead_time": "5-7 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Steel",
        "color": "Platinum",
        "brand": "Steelcase",
        "width": 36,
        "depth": 18,
        "height": 52,
        "weight": 185,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Full-extension drawers", "Central locking", "Anti-tip mechanism", "Counterweight"],
    },
    {
        "title": "Herman Miller Tu 3-Drawer Mobile Pedestal",
        "category": "Storage",
        "vendor": "Office Furniture Liquidators",
        "price": 395.00,
        "moq": 1,
        "qty": 28,
        "sku": "HM-TU-3MP",
        "upc": "886781005002",
        "lead_time": "3-5 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1595846519845-68e298c2edd8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Steel",
        "color": "Studio White",
        "brand": "Herman Miller",
        "width": 15.75,
        "depth": 22.5,
        "height": 22,
        "weight": 68,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Soft-close drawers", "Cushion top optional", "Keyed lock", "Full extension"],
    },
    {
        "title": "HON Brigade 5-Drawer Vertical File",
        "category": "Storage",
        "vendor": "National Business Furniture",
        "price": 425.00,
        "moq": 1,
        "qty": 10,
        "sku": "HON-BRIG-5V",
        "upc": "886781005003",
        "lead_time": "3-5 Business Days",
        "fob": "Chicago, IL",
        "image_url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
        "room_type": "Private Office",
        "style": "Traditional",
        "material": "Steel",
        "color": "Charcoal",
        "brand": "HON",
        "width": 15,
        "depth": 25,
        "height": 60,
        "weight": 145,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": False,
        "features": ["Letter-size", "Core-removable lock", "Aluminum handles", "High-sided drawers"],
    },

    # ===== BOOKCASES & SHELVING =====
    {
        "title": "Steelcase Currency 5-High Open Bookcase",
        "category": "Storage",
        "vendor": "Ideal Office Supply",
        "price": 695.00,
        "moq": 1,
        "qty": 8,
        "sku": "SC-CURR-5HI",
        "upc": "886781005010",
        "lead_time": "5-7 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Virginia Walnut",
        "brand": "Steelcase",
        "width": 36,
        "depth": 15,
        "height": 66,
        "weight": 125,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["Adjustable shelves", "Steel frame", "Wall anchor included"],
    },
    {
        "title": "Knoll Anchor Storage 3-High with Doors",
        "category": "Storage",
        "vendor": "Corporate Interiors",
        "price": 895.00,
        "moq": 1,
        "qty": 6,
        "sku": "KN-ANCH-3HD",
        "upc": "886781005011",
        "lead_time": "7-10 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Laminate/Steel",
        "color": "White",
        "brand": "Knoll",
        "width": 36,
        "depth": 18,
        "height": 42,
        "weight": 145,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": True,
        "features": ["Concealed storage", "Soft-close doors", "Adjustable shelves"],
    },

    # ===== RECEPTION FURNITURE =====
    {
        "title": "Steelcase Turnstone Campfire Big Lounge",
        "category": "Lounge & Reception",
        "vendor": "Ideal Office Supply",
        "price": 1295.00,
        "moq": 1,
        "qty": 4,
        "sku": "SC-CAMP-BIG",
        "upc": "886781006001",
        "lead_time": "7-10 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "room_type": "Lobby",
        "style": "Modern",
        "material": "Fabric/Wood",
        "color": "Buzz2 Blue",
        "brand": "Steelcase",
        "width": 88,
        "depth": 36,
        "height": 32,
        "weight": 165,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": False,
        "features": ["Modular design", "Integrated table", "USB charging"],
    },
    {
        "title": "Herman Miller Swoop Lounge Chair",
        "category": "Lounge & Reception",
        "vendor": "Office Furniture Liquidators",
        "price": 1895.00,
        "moq": 1,
        "qty": 6,
        "sku": "HM-SWOOP-CH",
        "upc": "886781006002",
        "lead_time": "7-10 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Leather/Steel",
        "color": "Camel",
        "brand": "Herman Miller",
        "width": 30,
        "depth": 32,
        "height": 34,
        "weight": 75,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": False,
        "features": ["Single-piece shell", "Premium leather", "Polished base"],
    },
    {
        "title": "Knoll Womb Chair with Ottoman",
        "category": "Lounge & Reception",
        "vendor": "Corporate Interiors",
        "price": 2995.00,
        "moq": 1,
        "qty": 2,
        "sku": "KN-WOMB-SET",
        "upc": "886781006003",
        "lead_time": "10-14 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800",
        "room_type": "Lobby",
        "style": "Mid-Century Modern",
        "material": "Fabric/Fiberglass",
        "color": "Cato Fire Red",
        "brand": "Knoll",
        "width": 40,
        "depth": 34,
        "height": 35,
        "weight": 85,
        "condition": "Preowned",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Includes ottoman", "Molded fiberglass shell", "Chrome base", "Original Saarinen design"],
    },
    {
        "title": "National Office Furniture Fringe Modular Seating",
        "category": "Lounge & Reception",
        "vendor": "National Business Furniture",
        "price": 795.00,
        "moq": 2,
        "qty": 12,
        "sku": "NOF-FRING-2S",
        "upc": "886781006004",
        "lead_time": "5-7 Business Days",
        "fob": "Jasper, IN",
        "image_url": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800",
        "room_type": "Lobby",
        "style": "Contemporary",
        "material": "Fabric/Wood",
        "color": "Slate Gray",
        "brand": "National",
        "width": 50,
        "depth": 30,
        "height": 32,
        "weight": 95,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": False,
        "features": ["2-seat module", "Power option", "Ganging brackets", "Multiple configurations"],
    },

    # ===== RECEPTION DESKS =====
    {
        "title": "Steelcase Currency Welcome Desk 72 inch",
        "category": "Desks",
        "vendor": "Ideal Office Supply",
        "price": 1695.00,
        "moq": 1,
        "qty": 3,
        "sku": "SC-CURR-REC72",
        "upc": "886781006010",
        "lead_time": "7-10 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800",
        "room_type": "Lobby",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Studio White",
        "brand": "Steelcase",
        "width": 72,
        "depth": 30,
        "height": 42,
        "weight": 225,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["Transaction counter", "ADA compliant", "Cable management", "Lockable storage"],
    },

    # ===== GUEST CHAIRS =====
    {
        "title": "HON Ignition 2.0 Guest Chair with Arms",
        "category": "Chairs",
        "vendor": "National Business Furniture",
        "price": 225.00,
        "moq": 2,
        "qty": 35,
        "sku": "HON-IGN2-GC",
        "upc": "886781007001",
        "lead_time": "3-5 Business Days",
        "fob": "Chicago, IL",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Private Office",
        "style": "Contemporary",
        "material": "Fabric/Steel",
        "color": "Iron Ore",
        "brand": "HON",
        "width": 24,
        "depth": 25,
        "height": 36,
        "weight": 32,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Sled base", "Fixed arms", "Stacking capability", "Wall saver legs"],
    },
    {
        "title": "Steelcase Reply Guest Chair",
        "category": "Chairs",
        "vendor": "Ideal Office Supply",
        "price": 345.00,
        "moq": 2,
        "qty": 20,
        "sku": "SC-REPLY-GC",
        "upc": "886781007002",
        "lead_time": "5-7 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1551298370-9d3d53bc4f48?w=800",
        "room_type": "Private Office",
        "style": "Modern",
        "material": "Mesh/Steel",
        "color": "Black",
        "brand": "Steelcase",
        "width": 23,
        "depth": 24,
        "height": 35,
        "weight": 28,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Mesh back", "Sled base", "Stackable", "Flex back"],
    },
    {
        "title": "Knoll Bertoia Side Chair",
        "category": "Chairs",
        "vendor": "Corporate Interiors",
        "price": 695.00,
        "moq": 2,
        "qty": 14,
        "sku": "KN-BERT-SIDE",
        "upc": "886781007003",
        "lead_time": "7-10 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Conference Room",
        "style": "Mid-Century Modern",
        "material": "Wire/Steel",
        "color": "Chrome",
        "brand": "Knoll",
        "width": 21.25,
        "depth": 22,
        "height": 30,
        "weight": 18,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": False,
        "features": ["Iconic design", "Welded steel wire", "Seat pad included"],
    },

    # ===== TASK/STOOL SEATING =====
    {
        "title": "Herman Miller Aeron Stool",
        "category": "Chairs",
        "vendor": "Office Furniture Liquidators",
        "price": 895.00,
        "moq": 1,
        "qty": 8,
        "sku": "HM-AERON-ST",
        "upc": "886781007010",
        "lead_time": "5-7 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Mesh/Aluminum",
        "color": "Graphite",
        "brand": "Herman Miller",
        "width": 27,
        "depth": 27,
        "height": 52,
        "weight": 48,
        "condition": "Refurbished",
        "warranty": "2 Years",
        "assembly_required": False,
        "features": ["Counter height", "Foot ring", "PostureFit SL", "Height adjustable"],
    },
    {
        "title": "Steelcase Leap Stool",
        "category": "Chairs",
        "vendor": "Ideal Office Supply",
        "price": 725.00,
        "moq": 1,
        "qty": 10,
        "sku": "SC-LEAP-ST",
        "upc": "886781007011",
        "lead_time": "5-7 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1589884629038-b631346a23c0?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Fabric/Steel",
        "color": "Buzz2 Black",
        "brand": "Steelcase",
        "width": 27,
        "depth": 24.75,
        "height": 51,
        "weight": 52,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": False,
        "features": ["Counter height", "Foot ring", "LiveBack technology", "4D arms"],
    },

    # ===== ACCESSORIES =====
    {
        "title": "Humanscale M8.1 Monitor Arm",
        "category": "Accessories",
        "vendor": "Ergonomic Solutions Inc",
        "price": 395.00,
        "moq": 1,
        "qty": 25,
        "sku": "HS-M81-ARM",
        "upc": "886781008001",
        "lead_time": "3-5 Business Days",
        "fob": "New York, NY",
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Aluminum/Steel",
        "color": "Silver",
        "brand": "Humanscale",
        "width": 4,
        "depth": 18,
        "height": 16,
        "weight": 12,
        "condition": "New",
        "warranty": "15 Years",
        "assembly_required": True,
        "features": ["Holds up to 42 lbs", "360 rotation", "Cable management", "Quick release VESA"],
    },
    {
        "title": "Ergotron LX Dual Monitor Arm",
        "category": "Accessories",
        "vendor": "Ergonomic Solutions Inc",
        "price": 449.00,
        "moq": 1,
        "qty": 30,
        "sku": "ERG-LX-DUAL",
        "upc": "886781008002",
        "lead_time": "3-5 Business Days",
        "fob": "St. Paul, MN",
        "image_url": "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Aluminum/Steel",
        "color": "Polished Aluminum",
        "brand": "Ergotron",
        "width": 6,
        "depth": 22,
        "height": 20,
        "weight": 15,
        "condition": "New",
        "warranty": "10 Years",
        "assembly_required": True,
        "features": ["Dual monitors up to 24 inch", "Side-by-side configuration", "CF motion technology"],
    },
    {
        "title": "Humanscale Keyboard Tray 6G System",
        "category": "Accessories",
        "vendor": "Ergonomic Solutions Inc",
        "price": 525.00,
        "moq": 1,
        "qty": 15,
        "sku": "HS-6G-TRAY",
        "upc": "886781008003",
        "lead_time": "5-7 Business Days",
        "fob": "New York, NY",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Aluminum/Steel",
        "color": "Black",
        "brand": "Humanscale",
        "width": 27,
        "depth": 11,
        "height": 6,
        "weight": 18,
        "condition": "New",
        "warranty": "15 Years",
        "assembly_required": True,
        "features": ["Negative tilt", "Mouse platform", "Self-adjusting mechanism"],
    },
    {
        "title": "Steelcase Dash Mini Desktop Organizer",
        "category": "Accessories",
        "vendor": "Ideal Office Supply",
        "price": 45.00,
        "moq": 5,
        "qty": 60,
        "sku": "SC-DASH-ORG",
        "upc": "886781008010",
        "lead_time": "3-5 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Steel/Plastic",
        "color": "White",
        "brand": "Steelcase",
        "width": 8,
        "depth": 6,
        "height": 4,
        "weight": 2,
        "condition": "New",
        "warranty": "1 Year",
        "assembly_required": False,
        "features": ["Phone holder", "Pen cups", "Card holder", "Removable dividers"],
    },

    # ===== PRIVACY SCREENS =====
    {
        "title": "Steelcase Sarto Screen 48x54",
        "category": "Cubicles & Partitions",
        "vendor": "Ideal Office Supply",
        "price": 395.00,
        "moq": 2,
        "qty": 18,
        "sku": "SC-SARTO-4854",
        "upc": "886781009001",
        "lead_time": "5-7 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Fabric/Aluminum",
        "color": "Heather Gray",
        "brand": "Steelcase",
        "width": 48,
        "depth": 2,
        "height": 54,
        "weight": 28,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["Tackable surface", "Freestanding", "Sound absorbing", "Modular"],
    },
    {
        "title": "Herman Miller Overlay Freestanding Screen",
        "category": "Cubicles & Partitions",
        "vendor": "Office Furniture Liquidators",
        "price": 495.00,
        "moq": 1,
        "qty": 12,
        "sku": "HM-OVER-60",
        "upc": "886781009002",
        "lead_time": "5-7 Business Days",
        "fob": "Zeeland, MI",
        "image_url": "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800",
        "room_type": "Open Office",
        "style": "Modern",
        "material": "Felt/Steel",
        "color": "Ocean Blue",
        "brand": "Herman Miller",
        "width": 60,
        "depth": 2.5,
        "height": 58,
        "weight": 35,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": False,
        "features": ["PET felt material", "Acoustic properties", "Magnetic accessory compatible"],
    },

    # ===== CAFE/BREAK ROOM =====
    {
        "title": "Steelcase Groupwork Round Table 42 inch",
        "category": "Tables",
        "vendor": "Ideal Office Supply",
        "price": 695.00,
        "moq": 1,
        "qty": 8,
        "sku": "SC-GRP-RD42",
        "upc": "886781010001",
        "lead_time": "5-7 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "room_type": "Break Room",
        "style": "Modern",
        "material": "Laminate/Steel",
        "color": "Designer White",
        "brand": "Steelcase",
        "width": 42,
        "depth": 42,
        "height": 29,
        "weight": 85,
        "condition": "Refurbished",
        "warranty": "90 Days",
        "assembly_required": True,
        "features": ["Round shape", "Central base", "Seats 4", "Power option available"],
    },
    {
        "title": "Knoll Saarinen Tulip Table 48 inch",
        "category": "Tables",
        "vendor": "Corporate Interiors",
        "price": 1895.00,
        "moq": 1,
        "qty": 4,
        "sku": "KN-TULIP-48",
        "upc": "886781010002",
        "lead_time": "10-14 Business Days",
        "fob": "East Greenville, PA",
        "image_url": "https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800",
        "room_type": "Break Room",
        "style": "Mid-Century Modern",
        "material": "Marble/Aluminum",
        "color": "Arabescato Marble",
        "brand": "Knoll",
        "width": 48,
        "depth": 48,
        "height": 28.5,
        "weight": 145,
        "condition": "Preowned",
        "warranty": "60 Days",
        "assembly_required": True,
        "features": ["Genuine marble top", "Cast aluminum base", "Iconic design", "Seats 4-6"],
    },
    {
        "title": "HON Motivate Cafe Height Stool",
        "category": "Chairs",
        "vendor": "National Business Furniture",
        "price": 165.00,
        "moq": 2,
        "qty": 24,
        "sku": "HON-MOT-CAFE",
        "upc": "886781010010",
        "lead_time": "3-5 Business Days",
        "fob": "Chicago, IL",
        "image_url": "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
        "room_type": "Break Room",
        "style": "Contemporary",
        "material": "Plastic/Steel",
        "color": "Onyx",
        "brand": "HON",
        "width": 21,
        "depth": 21,
        "height": 44,
        "weight": 22,
        "condition": "New",
        "warranty": "Limited Lifetime",
        "assembly_required": True,
        "features": ["Cafe height", "Stacking", "Four-leg base", "Foot ring"],
    },

    # ===== WHITEBOARDS & COLLABORATION =====
    {
        "title": "Steelcase Roam Mobile Whiteboard 75 inch",
        "category": "Accessories",
        "vendor": "Ideal Office Supply",
        "price": 2495.00,
        "moq": 1,
        "qty": 3,
        "sku": "SC-ROAM-75",
        "upc": "886781011001",
        "lead_time": "7-10 Business Days",
        "fob": "Grand Rapids, MI",
        "image_url": "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800",
        "room_type": "Conference Room",
        "style": "Modern",
        "material": "Glass/Steel",
        "color": "Arctic White",
        "brand": "Steelcase",
        "width": 75,
        "depth": 24,
        "height": 68,
        "weight": 185,
        "condition": "New",
        "warranty": "12 Years",
        "assembly_required": True,
        "features": ["For Microsoft Surface Hub 2S", "Mobile cart", "Rotating screen", "Cable management"],
    },
    {
        "title": "Quartet Infinity Glass Marker Board 72x48",
        "category": "Accessories",
        "vendor": "National Business Furniture",
        "price": 495.00,
        "moq": 1,
        "qty": 10,
        "sku": "QRT-INF-7248",
        "upc": "886781011002",
        "lead_time": "3-5 Business Days",
        "fob": "Chicago, IL",
        "image_url": "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800",
        "room_type": "Conference Room",
        "style": "Modern",
        "material": "Tempered Glass",
        "color": "White",
        "brand": "Quartet",
        "width": 72,
        "depth": 0.5,
        "height": 48,
        "weight": 65,
        "condition": "New",
        "warranty": "15 Years",
        "assembly_required": True,
        "features": ["Ghost-free", "Magnetic", "Mounting hardware included", "Non-porous surface"],
    },
]


def connect_db():
    """Connect to the database"""
    return psycopg2.connect(**DB_CONFIG, cursor_factory=RealDictCursor)


def seed_database():
    """Insert all furniture products into the database"""
    conn = connect_db()
    cur = conn.cursor()

    inserted = 0
    skipped = 0

    for product in FURNITURE_DATA:
        # Check if product already exists by SKU
        cur.execute("SELECT id FROM products WHERE sku = %s", (product["sku"],))
        if cur.fetchone():
            print(f"Skipping duplicate: {product['title']} (SKU: {product['sku']})")
            skipped += 1
            continue

        # Generate random dates within the last 30 days
        days_ago = random.randint(0, 30)
        offer_date = datetime.now() - timedelta(days=days_ago)

        # Random expiration date 30-90 days from now
        exp_days = random.randint(30, 90)
        exp_date = (datetime.now() + timedelta(days=exp_days)).strftime("%Y-%m-%d")

        try:
            cur.execute("""
                INSERT INTO products (
                    title, category, vendor, price, moq, qty, sku, upc,
                    lead_time, exp_date, fob, image_url, out_of_stock,
                    offer_date, date_added, room_type, style, material, color, brand,
                    width, depth, height, weight, condition, warranty,
                    assembly_required, features
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
            """, (
                product["title"],
                product["category"],
                product["vendor"],
                product["price"],
                product["moq"],
                product["qty"],
                product["sku"],
                product.get("upc"),
                product["lead_time"],
                exp_date,
                product["fob"],
                product["image_url"],
                False,  # out_of_stock
                offer_date,
                datetime.now(),
                product.get("room_type"),
                product.get("style"),
                product.get("material"),
                product.get("color"),
                product.get("brand"),
                product.get("width"),
                product.get("depth"),
                product.get("height"),
                product.get("weight"),
                product.get("condition", "New"),
                product.get("warranty"),
                product.get("assembly_required", False),
                product.get("features"),
            ))
            inserted += 1
            print(f"Inserted: {product['title']}")
        except Exception as e:
            print(f"Error inserting {product['title']}: {e}")
            conn.rollback()
            continue

    conn.commit()
    cur.close()
    conn.close()

    print(f"\n{'='*50}")
    print(f"Seeding complete!")
    print(f"Inserted: {inserted} products")
    print(f"Skipped: {skipped} duplicates")
    print(f"Total in data: {len(FURNITURE_DATA)}")


if __name__ == "__main__":
    seed_database()
